### PR TITLE
fix: db-pre-config function failing with pg reserved words

### LINKED ISSUE #4380: Using PGREST_DB_PRE_CONFIG w/out the underlying config function yields a confusing error
### Environment

* PostgreSQL version: postgres:17
* PostgREST version: postgrest/postgrest:v13.0.7
* Operating system: Docker Desktop 4.26.1 on Mac OS 15.1.1

### Description of issue

Describe the behavior you expected vs the actual behavior. Include:

This on startup:
```
pg         | 2025-10-03 21:48:33.517 UTC [51] LOG:  unexpected EOF on client connection with an open transaction
postgrest exited with code 1
postgrest  | 03/Oct/2025:21:48:35 +0000: Listening for database notifications on the "pgrst" channel
postgrest  | 03/Oct/2025:21:48:35 +0000: Successfully connected to PostgreSQL 17.6 (Debian 17.6-2.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
postgrest  | 03/Oct/2025:21:48:35 +0000: Connection Pool initialized with a maximum size of 15 connections
pg         | 2025-10-03 21:48:35.276 UTC [53] ERROR:  syntax error at or near "true" at character 566
pg         | 2025-10-03 21:48:35.276 UTC [53] STATEMENT:  WITH
pg         |    role_setting AS (
pg         |      SELECT setdatabase as database,
pg         |             unnest(setconfig) as setting
pg         |      FROM pg_catalog.pg_db_role_setting
pg         |      WHERE setrole = CURRENT_USER::regrole::oid
pg         |        AND setdatabase IN (0, (SELECT oid FROM pg_catalog.pg_database WHERE datname = CURRENT_CATALOG))
pg         |    ),
pg         |    kv_settings AS (
pg         |      SELECT database,
pg         |             substr(setting, 1, strpos(setting, '=') - 1) as k,
pg         |             substr(setting, strpos(setting, '=') + 1) as v
pg         |      FROM role_setting
pg         |      UNION
pg         |      SELECT
pg         |        null as database,
pg         |        x as k,
pg         |        current_setting(x, true) as v
pg         |      FROM unnest($1) x
pg         |      JOIN true() _ ON TRUE
pg         |    )
pg         |    SELECT DISTINCT ON (key)
pg         |           replace(k, 'pgrst.', '') AS key,
pg         |           v AS value
pg         |    FROM kv_settings
pg         |    WHERE k = ANY($1) AND v IS NOT NULL
pg         |    ORDER BY key, database DESC NULLS LAST;
postgrest  | 03/Oct/2025:21:48:35 +0000: This is probably a bug in PostgREST, please report it at https://github.com/PostgREST/postgrest/issues. {"code":"42601","details":null,"hint":null,"message":"syntax error at or near \"true\""}
postgrest  | 03/Oct/2025:21:48:35 +0000: Failed to query database settings for the config parameters.{"code":"42601","details":null,"hint":null,"message":"syntax error at or near \"true\""}
postgrest  | postgrest: thread killed
```

Discovered by having ChatGPT through in a gratuitous PGREST_DB_PRE_CONFIG into a docker-compose.yaml where it had no business being.

### PR DESCRIPTION
**Pull request by taimoorzaeem**
When `db-pre-config` is accidentally set to a pg reserved word like "true", it fails with a confusing error. The function names should be properly quoted to avoid such errors. This commit resolves the mentioned issue by quoting the pre-config function name.

Closes #4380.

### CODE REVIEW

File: src/PostgREST/Config/Database.hs [hunk 1]
```diff
@@ -203,3 +204,14 @@ param = HE.param . HE.nonNullable
...
+-- |
+-- >>> quotePreConfFunc "postgrest.pre_config"
+-- "\"postgrest\".\"pre_config\""
+--
+-- >>> quotePreConfFunc "true"
+-- "\"true\""
+quotePreConfFunc :: Text -> Text
+quotePreConfFunc f = T.intercalate "." $ map escapeIdent $ T.split (== '.') f
+    where
+      escapeIdent id = "\"" <> id <> "\""
```
Comment (wolfgangwalther) [inline src/PostgREST/Config/Database.hs]: Don't we have a helper function for this somewhere already?

Comment (steve-chavez) [reply src/PostgREST/Config/Database.hs]: Maybe https://github.com/PostgREST/postgrest/blob/3db05612ff3a6abb1d509aac0c2bfdd4f00dad44/src/PostgREST/Query/SqlFragment.hs#L166-L167

Comment (taimoorzaeem) [reply src/PostgREST/Config/Database.hs]: https://github.com/PostgREST/postgrest/blob/66161104bf09584dd0bef6539b93ba9f0d0a020e/src/PostgREST/Query/SqlFragment.hs#L245-L249

We have this, but it gives a `Snippet` and not `Text`. Also, the `Config/Database.hs` module is currently free of `Query` and `SchemaCache` modules, so let's not pollute it with that as it would make the dependency graph even weirder.

I think long term solution would be to have our own Prelude as discussed in https://github.com/PostgREST/postgrest/issues/1804#issuecomment-3254810274. For now I have handled it by quoting it by a new function `quoteQi`.

**Review by steve-chavez — APPROVED** [review]
Tested it manually. Nice work 💯

File: src/PostgREST/SchemaCache/Identifiers.hs [hunk 2]
```diff
@@ -39,6 +40,12 @@ dumpQi :: QualifiedIdentifier -> Text
 dumpQi (QualifiedIdentifier s i) =
   (if T.null s then mempty else s <> ".") <> i
 
+quoteQi :: QualifiedIdentifier -> Text
+quoteQi (QualifiedIdentifier s i) =
+  (if T.null s then mempty else quoteIdent s <> ".") <> quoteIdent i
+  where
+    quoteIdent ident = "\"" <> ident <> "\""
```
Comment (steve-chavez) [inline src/PostgREST/SchemaCache/Identifiers.hs]: Oh, one sec. This doesn't escape the `"` right? 

---

If you test it like so:

```
$ PGRST_DB_PRE_CONFIG="sel\"ect" postgrest-with-postgresql-15 -f test/spec/fixtures/load.sql postgrest-run
```

It wil give a bad error:

```sql
24/Oct/2025:13:02:55 -0500: This is probably a bug in PostgREST, please report it at https://github.com/PostgREST/postgrest/issues. {"code":"42601","details":null,"hint":null,"message":"unterm
inated quoted identifier at or near \"\"() _ ON TRUE\n)\nSELECT DISTINCT ON (key)\n       replace(k, 'pgrst.', '') AS key,\n       v AS value\nFROM kv_settings\nWHERE k = ANY($1) AND v IS NOT 
NULL\nORDER BY key, database DESC NULLS LAST;\""}
24/Oct/2025:13:02:55 -0500: Failed to query database settings for the config parameters.{"code":"42601","details":null,"hint":null,"message":"unterminated quoted identifier at or near \"\"() _
 ON TRUE\n)\nSELECT DISTINCT ON (key)\n       replace(k, 'pgrst.', '') AS key,\n       v AS value\nFROM kv_settings\nWHERE k = ANY($1) AND v IS NOT NULL\nORDER BY key, database DESC NULLS LAST
;\""}
postgrest: thread killed

```

File: src/PostgREST/Config/Database.hs (hunk 1 above)
Comment (steve-chavez) [reply src/PostgREST/Config/Database.hs]: > I think long term solution would be to have our own Prelude as discussed in https://github.com/PostgREST/postgrest/issues/1804#issuecomment-3254810274. For now I have handled it by quoting it by a new function quoteQi.

Maybe instead we can move 

https://github.com/PostgREST/postgrest/blob/4643eaf7bf9a3633720e619e7eea0ad3b705034a/src/PostgREST/Query/SqlFragment.hs#L166-L167

To `src/PostgREST/SchemaCache/Identifiers.hs`?

Comment (taimoorzaeem) [reply src/PostgREST/Config/Database.hs]: > Maybe instead we can move
> [...] 
> To `src/PostgREST/SchemaCache/Identifiers.hs`?

Yes, lemme refactor this. :+1:

File: src/PostgREST/SchemaCache/Identifiers.hs (hunk 2 above)
Comment (taimoorzaeem) [reply src/PostgREST/SchemaCache/Identifiers.hs]: Oh, missed that. Fixed now. :+1:

File: src/PostgREST/SchemaCache/Identifiers.hs [hunk 3]
```diff
@@ -41,6 +42,10 @@ dumpQi :: QualifiedIdentifier -> Text
 dumpQi (QualifiedIdentifier s i) =
   (if T.null s then mempty else s <> ".") <> i
 
+quoteQi :: QualifiedIdentifier -> Text
+quoteQi (QualifiedIdentifier s i) =
+  (if T.null s then mempty else escapeIdent s <> ".") <> escapeIdent i
```
Comment (steve-chavez) [inline src/PostgREST/SchemaCache/Identifiers.hs:47]: Just noticed the `dumpQi`  is too similar to `quoteQi`.

Shouldn't we stay with `quoteQi` and drop `dumpQi`?

https://github.com/PostgREST/postgrest/blob/23750e644fca895b0153f84c62df64bf16166a78/src/PostgREST/SchemaCache/Identifiers.hs#L38-L40

Comment (taimoorzaeem) [reply src/PostgREST/SchemaCache/Identifiers.hs:47]: The `dumpQi` function is used in the config dumping, here:

https://github.com/PostgREST/postgrest/blob/75d4131aa67a8169e43082ff5c2e3cd995b576e7/src/PostgREST/Config.hs#L171

With `quoteQi` we set the config to `db-pre-config="true"`, but then get `db-pre-config="\"true\""` in the config dump, which is different, right?

Comment (steve-chavez) [reply src/PostgREST/SchemaCache/Identifiers.hs:47]: Right, on second thought we shouldn't change usage on those other places on this PR.

But we definitely some clarification between `dumpQi/quoteQi`, even if it's just a comment on the function saying why we have two functions that are so similar. That can be done on another PR.

(if we can stick to a single function that'd be even better)

Comment (taimoorzaeem) [reply src/PostgREST/SchemaCache/Identifiers.hs:47]: Alright. I think we can move `dumpQi` to `Config.hs` module because that's the only place it's used. This should eliminate at least some confusion. Done that on #4435.

**Comment by taimoorzaeem** [comment]
@wolfgangwalther To backport this to `v14`, we need to first backport #4432 right? Could you please create the `backport v14` label? Or we can just do this manually in one PR too.

**Comment by wolfgangwalther** [comment]
> Could you please create the `backport v14` label?

Added that label to the other PR.
