### PR TITLE
Fix PGRST002 errors not logging the JSON messages and reloading the schema unnecessarily on startup

### LINKED ISSUE #4129: Requests are rejected immediately when loading the Schema Cache on startup
### Environment

* PostgreSQL version: 17.5
* PostgREST version: Docker 13.0.2
* Operating system: MacOS

### Description of issue

Right now, when the Schema Cache is reloaded, the requests wait until the schema is ready, e. g. this test:

https://github.com/PostgREST/postgrest/blob/69072116be330f0a0a90145ea291f423aa5bc5c2/test/io/test_big_schema.py#L10-L11

However this does not happen on startup. It does not wait for the Schema Cache and rejects the request immediately with a 503 response (as a side note, the JSON body with the error response is not logged):

```bash
06/Jun/2025:00:12:57 +0000: Config reloaded
192.168.215.1 - web_anon [06/Jun/2025:00:12:57 +0000] "GET /films HTTP/1.1" 503 119 "" "curl/8.7.1"
192.168.215.1 - web_anon [06/Jun/2025:00:12:57 +0000] "GET /films HTTP/1.1" 503 119 "" "curl/8.7.1"
192.168.215.1 - web_anon [06/Jun/2025:00:12:57 +0000] "GET /films HTTP/1.1" 503 119 "" "curl/8.7.1"
06/Jun/2025:00:12:57 +0000: Schema cache queried in 28.4 milliseconds
```

The client receives this error message:

```json
{"code":"PGRST002","details":null,"hint":null,"message":"Could not query the database for the schema cache. Retrying."}
```

### Expected behavior

To keep consistency, PostgREST should also wait until the Schema Cache is loaded on startup.

### PR DESCRIPTION
**Pull request by laurenceisla**
Closes #4129 as mentioned in the revision https://github.com/PostgREST/postgrest/issues/4129#issuecomment-3354387811.

### CODE REVIEW

File: src/PostgREST/Error.hs [hunk 1]
```diff
@@ -717,7 +717,7 @@ instance ErrorBody Error where
   hint (ApiRequestError err) = hint err
   hint (SchemaCacheErr err)  = hint err
   hint (JwtErr err)          = hint err
-  hint NoSchemaCacheError    = Nothing
+  hint NoSchemaCacheError    = Just "This usually happens when PostgREST is starting up. Try again later."
```
Comment (steve-chavez) [inline src/PostgREST/Error.hs]: Can we get the requests to wait like what happens after the schema cache is loaded? This would be the ideal behavior.

File: src/PostgREST/App.hs [hunk 2]
```diff
@@ -109,10 +109,11 @@ postgrest logLevel appState connWorker =
...
 
         response <- either Error.errorResponseFor identity <$> eitherResponse
-        -- Launch the connWorker when the connection is down.  The postgrest
+        -- Launch the connWorker when the connection is down. The postgrest
         -- function can respond successfully (with a stale schema cache) before
-        -- the connWorker is done.
-        when (isServiceUnavailable response) connWorker
+        -- the connWorker is done. However it won't launch the connWorker if
+        -- the schema cache was not loaded beforehand, i.e. on startup.
+        when (isServiceUnavailable response && isJust maybeSchemaCache) connWorker
```
Comment (steve-chavez) [inline src/PostgREST/App.hs]: This is good. When the scache is Nothing then we don't retry.

File: src/PostgREST/Error.hs (hunk 1 above)
Comment (steve-chavez) [reply src/PostgREST/Error.hs]: @laurenceisla Maybe if we drop the maybe from:

https://github.com/PostgREST/postgrest/blob/706a4894308937fa67bac5cbb0c76a6b0dc8f9d1/src/PostgREST/AppState.hs#L85

The waiting will automatically happen

Comment (laurenceisla) [reply src/PostgREST/Error.hs]: > Maybe if we drop the maybe

Tried it out and did not work. There is no `Nothing` schema cache if this is the case, we have to use one with empty values (e.g. empty tables, empty functions, etc.). It doesn't wait automatically, it returns an immediate `404` response with this initial schema instead of a `503` with the `PGRST002` error.

> Can we get the requests to wait like what happens after the schema cache is loaded? This would be the ideal behavior.

I also think this would be ideal, it would also stop flooding the logs with `PGRST002` errors for apps with a lot of requests. However this would be a different behavior from what we currently do when we restart the schema and respond before the schema is loaded. For example:

```
-- On startup:

Config reload
-- Requests are immediately rejected here with `PGRST002` errors
Schema queried
-- Requests wait until schema is loaded
Schema loaded

-- On a Schema Cache Reload:

Config reload
-- Requests are immediately handled using the stale schema
Schema queried
-- Requests wait until schema is loaded
Schema Loaded
```

So instead of immediately reject the request with `PGRST002` we would wait instead. I'll check further on how to do that.

Comment (steve-chavez) [reply src/PostgREST/Error.hs]: Got it. Maybe this is too complicated right now. As it is, the PR is an improvement though as it surfaces an error.

The only problem is that the message looks a bit sloppy :thinking:. I can't think of a better choice, maybe leave it as before or add a TODO comment.

```suggestion
```

Comment (laurenceisla) [reply src/PostgREST/Error.hs]: > Got it. Maybe this is too complicated right now. 

Yeah, can confirm that it's not so trivial.

> The only problem is that the message looks a bit sloppy 🤔. I can't think of a better choice, maybe leave it as before or add a TODO comment.

Yes, wasn't too convinced either. I'll remove it.

File: src/PostgREST/App.hs [hunk 3]
```diff
@@ -109,10 +109,11 @@ postgrest logLevel appState connWorker =
             runExceptT $ postgrestResponse appState appConf maybeSchemaCache authResult req
 
         response <- either Error.errorResponseFor identity <$> eitherResponse
-        -- Launch the connWorker when the connection is down.  The postgrest
+        -- Launch the connWorker when the connection is down. The postgrest
         -- function can respond successfully (with a stale schema cache) before
-        -- the connWorker is done.
-        when (isServiceUnavailable response) connWorker
+        -- the connWorker is done. However it won't launch the connWorker if
+        -- the schema cache was not loaded beforehand, i.e. on startup.
```
Comment (steve-chavez) [inline src/PostgREST/App.hs]: Please elaborate more on that comment. It says it does something but not **why** (because it's wasteful to rerun the scache queries again if it's not completed anyway?)

You can also link to https://github.com/PostgREST/postgrest/issues/3704. The most detail the better because this part is complex and I'm not sure if it's all covered on tests.

File: test/io/test_io.py [hunk 4]
```diff
@@ -1871,6 +1871,35 @@ def test_pgrst_log_503_client_error_to_stderr(defaultenv):
         assert any(log_message in line for line in output)
 
 
+def test_pgrst_log_503_no_schema_cache_startup_error_to_stderr(
+    defaultenv, metapostgrest
+):
+    "Should log the 503 error message when the schema cache is not loaded on startup and not reload the schema cache"
```
Comment (steve-chavez) [inline test/io/test_io.py]: > Fix reloading the Schema Cache unnecessarily on a `PGRST002` error by @laurenceisla in #4367

Is this proving the above too? If so, why not use https://docs.postgrest.org/en/v13/references/observability.html#pgrst-schema-cache-loads-total instead? It would be much more clear.

Comment (steve-chavez) [inline test/io/test_io.py]: This second part is not too clear, I'd suggest rephrasing or splitting into two tests
```suggestion
    "Should log the 503 error message when the schema cache is not loaded on startup
```

File: src/PostgREST/App.hs [hunk 5]
```diff
@@ -109,10 +109,13 @@ postgrest logLevel appState connWorker =
...
         response <- either Error.errorResponseFor identity <$> eitherResponse
-        -- Launch the connWorker when the connection is down.  The postgrest
+        -- Launch the connWorker when the connection is down. The postgrest
         -- function can respond successfully (with a stale schema cache) before
-        -- the connWorker is done.
-        when (isServiceUnavailable response) connWorker
+        -- the connWorker is done. However, when there's an empty schema cache
+        -- postgrest responds with the error `PGRST002`; this means that the schema
+        -- cache is still loading, so we don't launch the connWorker here because
+        -- it would duplicate the loading process, e.g. https://github.com/PostgREST/postgrest/issues/3704
```
Comment (steve-chavez) [inline src/PostgREST/App.hs:117]: Just so we don't forget, this might be true:
```suggestion
        -- it would duplicate the loading process, e.g. https://github.com/PostgREST/postgrest/issues/3704
        -- TODO: this process may be unnecessary when the Listener is enabled. Revisit once https://github.com/PostgREST/postgrest/issues/1766 is done
```

File: test/io/test_io.py (hunk 4 above)
Comment (laurenceisla) [reply test/io/test_io.py]: > Is this proving the above too?

Yes

> If so, why not use https://docs.postgrest.org/en/v13/references/observability.html#pgrst-schema-cache-loads-total instead? It would be much more clear.

Oh, forgot about that metric, it's much clearer now! I separated it in another test (can confirm that it fails in `main` cause it returns `2.0` reloads there).
