### PR TITLE
fix(error): leaking table and function names when calculating hint

### LINKED ISSUE #4675: Fuzzy distance is too high for table hint
## Problem

The hints were meant to help the user with typos, but currently:

```http
GET /users?select=* 

{
  "code": "PGRST205",
  "details": null,
  "hint": "Perhaps you meant the table 'public.markers'",
  "message": "Could not find the table 'public.users' in the schema cache"
}

GET /employee_locations?select=*

{
  "code": "PGRST205",
  "details": null,
  "hint": "Perhaps you meant the table 'public.employees'",
  "message": "Could not find the table 'public.employee_locations' in the schema cache"
}

GET /clientsxxxxxxxxxxxxxx

{
  "code":"PGRST205",
  "details":null,
  "hint":"Perhaps you meant the table 'test.clients'",
  "message":"Could not find the table 'test.clientsxxxxxxxxxxxxxx' in the schema cache"
} 
```

And finally we don't get a hint with:

```http
GET /clientsxxxxxxxxxxxxxx

{
  "code":"PGRST205",
  "details":null,
  "hint":null,
  "message":"Could not find the table 'test.clientsxxxxxxxxxxxxxxx' in the schema cache"
}
```

So the fuzzy distance is too high. It looks like it's 14.

This could be considered a vulnerability since even with `openapi-mode=follow-privileges` it can allow a user to enumerate tables in a schema, even when the user doesn't have any privileges on them.

## Solution

Use a max fuzzy distance of 3. Same as on PostgreSQL ([ref](https://github.com/postgres/postgres/blob/851f6649cc18c4b482fa2b6afddb65b35d035370/src/backend/parser/parse_relation.c#L72)).

## Notes

- Same problem should be present on functions and embeddings

### PR DESCRIPTION
**Pull request by taimoorzaeem**
Increase similarity score to `0.75` from `0.33` for table and functions
error hint.

Closes #4675.

### CODE REVIEW

File: src/PostgREST/Error.hs [hunk 1]
```diff
@@ -375,16 +376,27 @@ noRpcHint schema procName params allProcs overloadedProcs =
     -- E.g. ["val", "param", "name"] into "(name, param, val)"
     listToText       = ("(" <>) . (<> ")") . T.intercalate ", " . sort
     possibleProcs
-      | null overloadedProcs = Fuzzy.getOne fuzzySetOfProcs procName
-      | otherwise            = (procName <>) <$> Fuzzy.getOne fuzzySetOfParams (listToText params)
+      | null overloadedProcs = Fuzzy.getOne fuzzySetOfProcs procName >>= checkFuzzyDistance procName
+      | otherwise            = (procName <>) <$> Fuzzy.getOne fuzzySetOfParams (listToText params) -- no fuzzy distance restriction on parameters hint? too aggresive or is that also a security concern?
```
Comment (taimoorzaeem) [inline src/PostgREST/Error.hs]: 3 characters seems too low for parameter hint so I didn't add this restriction on parameters hint. Thoughts?

EDIT: For example, we want to keep the hint when user calls `add_them(a,b,smth_else)` and hint shows `add_them(a,b)`.

Comment (steve-chavez) [reply src/PostgREST/Error.hs]: @taimoorzaeem Agree, no problem on the function parameters since there are no privileges on them.

File: test/spec/Feature/Query/InsertSpec.hs [hunk 2]
```diff
@@ -483,7 +483,7 @@ spec actualPgVersion = do
             {"id": 204, "body": "yyy"},
             {"id": 205, "body": "zzz"}]|]
           `shouldRespondWith`
-          [json| {"code":"PGRST205","details":null,"hint":"Perhaps you meant the table 'test.articles'","message":"Could not find the table 'test.garlic' in the schema cache"} |]
+          [json| {"code":"PGRST205","details":null,"hint":null,"message":"Could not find the table 'test.garlic' in the schema cache"} |]
           { matchStatus  = 404
```
Comment (steve-chavez) [inline test/spec/Feature/Query/InsertSpec.hs:487]: Shoot, this should have raised an alarm before. Our fuzzy search was so inclusive that it thought `garlic` and `articles` were cousins 😅

**Comment by wolfgangwalther** [comment]
Instead of doing the full fuzzy search first and then checking the levenshtein distance on the result, I think it would be better if the distance check was part of the algorithm already. I think PostgreSQL does the same. Does that mean this kind of change should actually happen further upstream? Could this also help with performance?

**Comment by steve-chavez** [comment]
>  Does that mean this kind of change should actually happen further upstream? Could this also help with performance?

This means on the Data.FuzzySet library right? If so, I agree.

**Comment by laurenceisla** [comment]
> This means on the Data.FuzzySet library right? If so, I agree.

I agree too, hopefully it's possible... the library hasn't seen an update in 3 years (we [have an issue](https://github.com/laserpants/fuzzyset-haskell/issues/9) that hasn't even been triaged too). We should keep looking for alternatives.

>  Could this also help with performance?

It seems so, [according to how they word it](https://www.postgresql.org/docs/current/fuzzystrmatch.html#FUZZYSTRMATCH-LEVENSHTEIN): "levenshtein_less_equal is an accelerated version of the Levenshtein function for use when only small distances are of interest." For future reference, the implementation can be found [here](https://github.com/postgres/postgres/blob/ce4fbe1ac6e9eeae08a825b7ce09efec3614632f/contrib/fuzzystrmatch/fuzzystrmatch.c#L234) and [here](https://github.com/postgres/postgres/blob/ce4fbe1ac6e9eeae08a825b7ce09efec3614632f/src/backend/utils/adt/levenshtein.c#L68) (maybe we can adapt it to Haskell).

**Comment by taimoorzaeem** [comment]
> It seems so, [according to how they word it](https://www.postgresql.org/docs/current/fuzzystrmatch.html#FUZZYSTRMATCH-LEVENSHTEIN): "levenshtein_less_equal is an accelerated version of the Levenshtein function for use when only small distances are of interest." For future reference, the implementation can be found [here](https://github.com/postgres/postgres/blob/ce4fbe1ac6e9eeae08a825b7ce09efec3614632f/contrib/fuzzystrmatch/fuzzystrmatch.c#L234) and [here](https://github.com/postgres/postgres/blob/ce4fbe1ac6e9eeae08a825b7ce09efec3614632f/src/backend/utils/adt/levenshtein.c#L68) (maybe we can adapt it to Haskell).

Agreed. Opened #4686 for this.

To fix the security vulnerability, this PR increases the similarity score threshold from `0.33` to `0.75` as discussed in https://github.com/PostgREST/postgrest/issues/4675#issuecomment-3999181496.

File: src/PostgREST/Error.hs [hunk 3]
```diff
@@ -375,16 +375,30 @@ noRpcHint schema procName params allProcs overloadedProcs =
     -- E.g. ["val", "param", "name"] into "(name, param, val)"
     listToText       = ("(" <>) . (<> ")") . T.intercalate ", " . sort
     possibleProcs
-      | null overloadedProcs = Fuzzy.getOne fuzzySetOfProcs procName
-      | otherwise            = (procName <>) <$> Fuzzy.getOne fuzzySetOfParams (listToText params)
+      | null overloadedProcs = getFuzzyHint Procedure fuzzySetOfProcs procName
+      | otherwise            = (procName <>) <$> getFuzzyHint Params fuzzySetOfParams (listToText params) -- For params, we stick to `getOne` which defaults to 0.33 min score, not a security risk to reveal params
```
Comment (steve-chavez) [inline src/PostgREST/Error.hs]:
```
-- For params, we stick to `getOne` which defaults to 0.33 min score, not a security risk to reveal params
```
Nice that we have this comment, should we move it to the `getFuzzyHint` function? (that's where I would read first).

File: test/spec/Feature/Query/DeleteSpec.hs [hunk 4]
```diff
@@ -116,7 +116,7 @@ spec =
       it "fails with 404" $
         request methodDelete "/foozle?id=eq.101" [] ""
           `shouldRespondWith`
-          [json| {"code":"PGRST205","details":null,"hint":"Perhaps you meant the table 'test.foo'","message":"Could not find the table 'test.foozle' in the schema cache"} |]
+          [json| {"code":"PGRST205","details":null,"hint":null,"message":"Could not find the table 'test.foozle' in the schema cache"} |]
```
Comment (steve-chavez) [inline test/spec/Feature/Query/DeleteSpec.hs:119]: So between `foo` and `foozle` the levenshtein distance is 3, if we were to reuse the postgres algorithm the hint would apply in this case. Perhaps we can tune the score to have a match here?

Comment (steve-chavez) [reply test/spec/Feature/Query/DeleteSpec.hs:119]: Not a deal breaker if not possible.

Comment (taimoorzaeem) [reply test/spec/Feature/Query/DeleteSpec.hs:119]: Yeah it's difficult, we'd have to lower the score too much for this case because the name length is too short. In production, identifiers like table and functions names are usually longer.

And so the 3 distance case will be covered with `0.75` score as soon as name length touches 9 to 12 characters.

File: src/PostgREST/Error.hs [hunk 5]
```diff
@@ -375,16 +375,30 @@ noRpcHint schema procName params allProcs overloadedProcs =
...
+data HintType
+  = Table
+  | Procedure
+  | Params
+
+-- | Get hint using Fuzzy Search with at least 0.75 similarity score
+getFuzzyHint :: HintType -> Fuzzy.FuzzySet -> Text -> Maybe Text
+getFuzzyHint hintType =
+  let minScore = 0.75 :: Double -- used for table and procedure name hints
+  in case hintType of
```
Comment (mkleczek) [inline src/PostgREST/Error.hs:398]: I would refactor it:

instead of having a dedicated enum and a function doing pattern match on this enum, it is IMO better to simply have three different functions:
* getTableFuzzyHint
* getProcedureFuzzyHint
* getParamsFuzzyHint

Callsites have to know which variant to call anyway (right now they have to pass a proper `HintType` instance) so let them call different functions instead.

Comment (steve-chavez) [reply src/PostgREST/Error.hs:398]: Hm, I don't agree here. I find it more readable as it is. Not sure if one or the other would result in more LOCs or stay the same.

@taimoorzaeem WDYT?

Comment (steve-chavez) [reply src/PostgREST/Error.hs:398]: I guess the intention of this single function was to reuse the `let minScore = 0.75 :: Double`?

If this would be split into different functions, then we would need a global for that or we'd have to repeat the number.

File: src/PostgREST/Error.hs [hunk 6]
```diff
@@ -375,16 +375,30 @@ noRpcHint schema procName params allProcs overloadedProcs =
...
 tableNotFoundHint schema tblName SchemaCache{dbTablesFuzzyIndex}
   = fmap (\tbl -> "Perhaps you meant the table '" <> schema <> "." <> tbl <> "'") perhapsTable
     where
-      perhapsTable = (`Fuzzy.getOne` tblName) =<< HM.lookup schema dbTablesFuzzyIndex
+      perhapsTable = (\fuzzySet -> getFuzzyHint Table fuzzySet tblName) =<< HM.lookup schema dbTablesFuzzyIndex
+
+data HintType
+  = Table
+  | Procedure
+  | Params
```
Comment (steve-chavez) [inline src/PostgREST/Error.hs]: Maybe
```suggestion
data HintType
  = HintTable
  | HintProcedure
  | HintParams
```

File: src/PostgREST/Error.hs (hunk 5 above)
Comment (taimoorzaeem) [reply src/PostgREST/Error.hs:398]: > Hm, I don't agree here. I find it more readable as it is.

Yes, agreed.

> I guess the intention of this single function was to reuse the `let minScore = 0.75 :: Double`?

Yup, that's exactly right.

Comment (mkleczek) [reply src/PostgREST/Error.hs:398]: > Hm, I don't agree here. I find it more readable as it is. Not sure if one or the other would result in more LOCs or stay the same.
> 

The suggestion is not really about readability (that's subjective) or LoC.

It is about coupling/cohesion.

Right now if you want to change logic for one type of object (let's say `Procedure`) you have to change shared unit (function) and risk breaking other (unrelated) objects' handling. The reason is that a single function has low cohesion - it has multiple responsibilities for which it does different things.

Low cohesion also makes refactoring more difficult: if for some (unknown at this moment) reason you would want to split hint processing for different object types into different modules, moving a function is simple, but splitting a function (and supporting type) is way more difficult because it affects all call sites.

Splitting it into different units (functions) increases cohesion and long term maintainability.

Not very important in this case but I try to keep cohesion as high as possible as a rule of thumb.

@taimoorzaeem - I'm fine with whatever you decide.

Comment (steve-chavez) [reply src/PostgREST/Error.hs:398]: > Low cohesion also makes refactoring more difficult: if for some (unknown at this moment) reason you would want to split hint processing for different object types into different modules, moving a function is simple, but splitting a function (and supporting type) is way more difficult because it affects all call sites.

> Splitting it into different units (functions) increases cohesion and long term maintainability.

Not disagreeing but so far hints have been always contained in this Errors module. If the need arises we can refactor to different functions. It's not so much code.

Will merge as is for now and do a patch release since https://github.com/PostgREST/postgrest/issues/4675 can be considered a vulnerability.
