### PR TITLE
fix: insert with missing=default uses column default before using domain default

### LINKED ISSUE #3706: Doing a bulk insert with `missing=default` uses the default value of the domain instead of the column
### Environment

* PostgreSQL version: 15.7
* PostgREST version: 12.2.3
* Operating system: NixOS

### Description of issue

As the title says. According to [the PostgreSQL docs](https://www.postgresql.org/docs/current/sql-createdomain.html):

> The default expression will be used in any insert operation that does not specify a value for the column. If a default value is defined for a particular column, it overrides any default associated with the domain. In turn, the domain default overrides any default value associated with the underlying data type.

To reproduce this:

```sql
create domain defdom as integer default 1;

create table test_defdom (
  id int primary key,
  val api.defdom default 10
);
```
```bash
curl -X POST 'localhost:3000/test_defdom?columns=id,val' \
  -H 'Content-Type: application/json' \
  -H 'Prefer: missing=default, return=representation' \
  -d '[{"id": 1}]'
```

Expected:

```json
[{"id":1,"val":10}]
```

Got:
```json
[{"id":1,"val":1}]
```

### Solution

Check if the defaults of the columns are not null first, otherwise use the domain default instead.

https://github.com/PostgREST/postgrest/blob/f21053dbee524bc12fe3e68fcee687c4a31a962d/src/PostgREST/SchemaCache.hs#L624-L629

### PR DESCRIPTION
**Pull request by taimoorzaeem**
Fixes #3706.

### CODE REVIEW

File: test/spec/Feature/Query/InsertSpec.hs [hunk 1]
```diff
@@ -572,6 +572,15 @@ spec actualPgVersion = do
               , matchHeaders = ["Preference-Applied" <:> "missing=default, return=representation"]
               }
 
+        it "inserts a COLUMN default before a DOMAIN default with missing=default" $
+          request methodPost "/evil_friends_with_column_default?columns=id,name" [("Prefer", "return=representation"), ("Prefer", "missing=default")]
```
Comment (steve-chavez) [inline test/spec/Feature/Query/InsertSpec.hs:576]: Are there tests that ensure a DOMAIN default will be applied in other cases?

Comment (taimoorzaeem) [reply test/spec/Feature/Query/InsertSpec.hs:576]: Yes, it is present just above this new test.

**Review by steve-chavez — APPROVED** [review]
