### PR TITLE
fix: filter on unselected columns in a table-valued function

### LINKED ISSUE #3965: Cannot use filters that are not selected in Table-Valued Functions
> [...] when using an rpc i cant filter for fields not in the select. I wanted to build an csv out of an filtered rpc, but i only want to include cols which are not part of a filter. 

 _Originally posted by @pebosi in [#3627](https://github.com/PostgREST/postgrest/issues/3627#issuecomment-2742476686)_

For example:

```bash
curl 'localhost:3000/rpc/getallprojects?select=id,client_id&name=like.OSX'
```
```json
{"code":"42703","details":null,"hint":null,"message":"column projects.name does not exist"} 
```

### PR DESCRIPTION
**Pull request by taimoorzaeem**
Closes #3965.

### CODE REVIEW

File: src/PostgREST/Plan.hs [hunk 1]
```diff
@@ -1028,6 +1029,22 @@ callPlan proc ApiRequest{} paramKeys args readReq = FunctionCall {
...
+    rpToFieldNames = logicTreesToFieldName . ReadPlan.where_
+
+    logicTreesToFieldName :: [CoercibleLogicTree] -> [FieldName]
+    logicTreesToFieldName = concatMap coLogicTreeToFieldNames
+
+    coLogicTreeToFieldNames :: CoercibleLogicTree -> [FieldName]
+    coLogicTreeToFieldNames = \case
+      CoercibleStmnt (CoercibleFilter{field=CoercibleField{cfName}}) -> [cfName]
+      CoercibleStmnt (CoercibleFilterNullEmbed _ cfName) -> [cfName]
+      CoercibleExpr _ _ clts -> concatMap coLogicTreeToFieldNames clts
```
Comment (taimoorzaeem) [inline src/PostgREST/Plan.hs:1046]: @laurenceisla I can't think of a test to `code-cov` these two lines? Any ideas?

Comment (laurenceisla) [reply src/PostgREST/Plan.hs:1046]: If I understand correctly, `CoercibleStmnt (CoercibleFilterNullEmbed ...)` is for `IS NULL` filters done to the embedded resource, like: `/rpc/getallprojects?select=client()&client=not.is.null`. The `CoercibleExpr` is for logical filters like: `/rpc/getallprojects?or=(id.eq.1,id.eq.2)` (just examples to illustrate, not sure if relevant to this PR).

File: src/PostgREST/Plan.hs [hunk 2]
```diff
@@ -1028,6 +1029,22 @@ callPlan proc ApiRequest{} paramKeys args readReq = FunctionCall {
...
+    rpToFieldNames :: ReadPlan -> [FieldName]
+    rpToFieldNames = logicTreesToFieldName . ReadPlan.where_
+
+    logicTreesToFieldName :: [CoercibleLogicTree] -> [FieldName]
+    logicTreesToFieldName = concatMap coLogicTreeToFieldNames
+
+    coLogicTreeToFieldNames :: CoercibleLogicTree -> [FieldName]
+    coLogicTreeToFieldNames = \case
+      CoercibleStmnt (CoercibleFilter{field=CoercibleField{cfName}}) -> [cfName]
+      CoercibleStmnt (CoercibleFilterNullEmbed _ cfName) -> [cfName]
```
Comment (taimoorzaeem) [inline src/PostgREST/Plan.hs:1045]: I tried `/rpc/getallprojects?select=id,clients(id)&clients.name=not.is.null` to cover this line but it didn't work. Hmm :thinking:.

Comment (laurenceisla) [reply src/PostgREST/Plan.hs:1045]: Ah, the filter should be done to the embedding itself, not to a column of the embedding, i.e. replace `clients.name=not.is.null` with `clients=not.is.null`.

Comment (laurenceisla) [reply src/PostgREST/Plan.hs:1045]: You may need to adapt it to your PR needs, so instead of replacing it, you could add another one (the current one seems relevant to your changes).

**Comment by taimoorzaeem** [comment]
I think we should also include an example for this in the docs, maybe in [horizontal-filtering](https://docs.postgrest.org/en/v12/references/api/tables_views.html#horizontal-filtering) or [embedded-filters](https://docs.postgrest.org/en/v12/references/api/resource_embedding.html#embedded-filters)?

File: src/PostgREST/Query/QueryBuilder.hs [hunk 3]
```diff
@@ -210,10 +211,17 @@ callPlanToQuery (FunctionCall qi params arguments returnsScalar returnsSetOfScal
...
-    returnedColumns
-      | null returnings = "*"
-      | otherwise       = intercalateSnippet ", " (pgFmtColumn (QualifiedIdentifier mempty "pgrst_call") <$> returnings)
+    returnedColumns = case returnings of
+      []    -> "*"
+      ["*"] -> pgFmtColumn (QualifiedIdentifier mempty "pgrst_call") "*"
+      _     -> intercalateSnippet ", " (pgFmtColumn (QualifiedIdentifier mempty "pgrst_call") <$> returnedColumns')
+        where
+          returnedColumns' = removeDups $ returnings ++ filterFields
+          removeDups = L.nub -- function to remove duplicates from list (possibly impact performance for very large lists)
```
Comment (steve-chavez) [inline src/PostgREST/Query/QueryBuilder.hs:224]: Since these fields are meant to be unique. Couldn't we use `Data.Set` instead to avoid this deduplication?

So `funCReturning` (returnings here) could be a Set instead of a List, then here we would just do an union with `S.fromList filterFields`?

That might be cleaner.

Additionally, not sure if large lists are a concern here since we don't expect so much fields thanks to the URL length limit.

Comment (taimoorzaeem) [reply src/PostgREST/Query/QueryBuilder.hs:224]: Yes, I think it would be cleaner to this in a refactor first to change the `returnings` to a `Set`.

**Review by steve-chavez — APPROVED** [review]
