### PR TITLE
Change tests to use postgres-json-schema instead of hjsonschema.

### LINKED ISSUE #934: Upgrade hjsonschema version(or remove it) in cabal file
We held it back because later versions made the test suite fail (even though it appears that they generate valid OpenAPI).

### PR DESCRIPTION
**Pull request by robx**
Fixes #934.

Embeds https://github.com/gavinwahl/postgres-json-schema.

Feels like gavinwahl/postgres-json-schema should be credited more properly, but I didn't find a good place to do so, and `test/fixtures/jwt.sql` does things the same.

(The tests pass with some other local changes and stackage LTS-13.23, haven't been able to test with cabal or older stackage, but I don't expect problems there.)

### CODE REVIEW

**Comment by robx** [comment]
The failure in in `build-test-9.4` was an hlint error.

The failures in `build-test-{10,11}`  seem real:

       status mismatch:
         expected: 200
         but got:  400
       body mismatch:
         expected: true
         but got:  {"hint":null,"details":"Token \"swagger\" is invalid.","code":"22P02","message":"invalid input syntax for type json"}

**Comment by robx** [comment]
My best guess at this point is that `postgres-json-schema` is incompatible with some change in postgresql 10.

There are some JSON-related changes in https://www.postgresql.org/docs/10/release-10.html, but nothing stands out...

**Comment by robx** [comment]
The test failures with PostgreSQL >= 10 appear to be due to bug related to the parsing of embedded JSON arguments, due to a change in the behavior of `record_to_json` in PostgreSQL.

**Comment by Qu4tro** [comment]
Hey there. I've tested this patch with both 9.4 and 11. Can you give this a go?

```
From 36a39c5dd98031bda1eabe97742cf786e75d174a Mon Sep 17 00:00:00 2001
From: Xavier Francisco
Date: Mon, 27 May 2019 20:53:44 +0100
Subject: [PATCH] Fix json encoding

---
 test/SpecHelper.hs | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/test/SpecHelper.hs b/test/SpecHelper.hs
index b576c8e..c3f476e 100644
--- a/test/SpecHelper.hs
+++ b/test/SpecHelper.hs
@@ -15,11 +15,11 @@ import Data.List            (lookup)
 import Network.Wai.Test     (SResponse (simpleBody, simpleHeaders, simpleStatus))
 import System.Environment   (getEnv)
 import System.Process       (readProcess)
+import Test.Hspec           (shouldSatisfy)
 import Text.Regex.TDFA      ((=~))
 
 
 import Network.HTTP.Types
-import Test.Hspec
 import Test.Hspec.Wai
 import Text.Heredoc
 
@@ -47,10 +47,10 @@ validateOpenApiResponse headers = do
   liftIO $
     (decode (simpleBody r) :: Maybe Value) `shouldSatisfy` isJust
   schema <- liftIO $ T.readFile "test/fixtures/openapi.json"
-  let args :: M.Map Text Text
+  let args :: M.Map Text Value
       args = M.fromList
-        [ ( "schema", schema )
-        , ( "data", decodeUtf8 . BL.toStrict . simpleBody $ r ) ]
+        [ ( "schema", fromMaybe "{}" . decode . toS $ schema )
+        , ( "data",   fromMaybe "{}" . decode . toS . decodeUtf8 . BL.toStrict . simpleBody $ r ) ]
       hdrs = acceptHdrs "application/json"
   request methodPost "/rpc/validate_json_schema" hdrs (encode args)
       `shouldRespondWith` "true"
-- 
2.21.0

```

File: test/SpecHelper.hs [hunk 1]
```diff
@@ -46,16 +45,19 @@ validateOpenApiResponse headers = do
     respHeaders `shouldSatisfy`
```
Comment (Qu4tro) [inline test/SpecHelper.hs]: Not really related to the PR, but could these checks be replaced by a single `shouldRespondWith` ?

**Comment by robx** [comment]
> Hey there. I've tested this patch with both 9.4 and 11. Can you give this a go?

Thanks! I'm a bit suspicious of it...

```
-  let args :: M.Map Text Text
+  let args :: M.Map Text Value
       args = M.fromList
-        [ ( "schema", schema )
-        , ( "data", decodeUtf8 . BL.toStrict . simpleBody $ r ) ]
+        [ ( "schema", fromMaybe "{}" . decode . toS $ schema )
+        , ( "data",   fromMaybe "{}" . decode . toS . decodeUtf8 . BL.toStrict . simpleBody $ r ) ]
```

- The `"{}"` is of type `Value` via a JSON `IsString` instance? Is that the JSON `"{}"` or `{}`?
- Regardless, I fear this might silently hide errors when the arguments are not valid JSON, since validating an empty JSON object or against an empty JSON schema might trivially succeed.

Is the idea to pass the JSON arguments as unquoted JSON? In that case, could I ask for your input on https://github.com/PostgREST/postgrest/pull/1306? Perhaps the bug there is not what I think it is.

File: test/SpecHelper.hs (hunk 1 above)
Comment (robx) [reply test/SpecHelper.hs]: My understanding is that `shouldRespondWith` requires specifying the full response body, which is why it's avoided here.

**Comment by Qu4tro** [comment]
You're right in both points (and it's unintentionally `"{}"`). Either way, I agree that having a default is not what we want here. I think we should check the decode call instead and fail the test if either decoding fails.

Yes, the idea is to pass a `Aeson.Value` instead of the quoted json.
Looking.

**Comment by robx** [comment]
Let's see then, pushed a change to not quote the arguments.

**Comment by robx** [comment]
I've rebased this onto master; the Postgres 9.6 vs Postgres 10 issue was resolved by embedding the JSON unquoted as suggested by @Qu4tro (though I'm still not sure what's really "right" here, but that can be discussed in #1306).

File: test/fixtures/jsonschema.sql [hunk 2]
```diff
@@ -0,0 +1,260 @@
+-- from gavinwahl/postgres-json-schema commit 5a257e19a1569a77b82e9182b0b7d9fc8b6f6382
+
```
Comment (steve-chavez) [inline test/fixtures/jsonschema.sql]: Regarding credit, how about if we copy the contents of https://github.com/gavinwahl/postgres-json-schema/blob/master/LICENSE here.

**Comment by steve-chavez** [comment]
@robx Great PR! I've been wanting to include `postgres-json-schema` for a while.

Been playing with it and doing tests like:
```sql
\set openapi $$`cat test/fixtures/openapi.json`$$::jsonb
\set openapi_pgrst $$`curl -s localhost:3000`$$::jsonb

select test.validate_json_schema(:openapi, :openapi_pgrst); -- true
select test.validate_json_schema(:openapi, '{"swagger": "2.0", "info": null, "paths": null}'); -- false
select test.validate_json_schema(:openapi, '{"swagger": "2.0", "info":{"version":"5.2.0","title":"PostgREST API"}, "paths": {}}'); -- true
```
And it works really well! I think we can safely replace hjsonschema.

See my review and after that I think we can merge.

File: test/fixtures/jsonschema.sql (hunk 2 above)
Comment (robx) [reply test/fixtures/jsonschema.sql]: Sounds good. Done.
