### PR TITLE
fix: improve jwt errors

### LINKED ISSUE #3600: Improve error messages for JWT verification errors
In #3598 I added a new IO test showing how many JWT errors we currently expose by just showing internal errors via `show`. Those are not very user friendly:

https://github.com/PostgREST/postgrest/blob/465170c7d6c51dace3faf68fbb4040353d5571c0/test/io/test_io.py#L78-L128

For at least a few of them we should improve the error message and maybe differentiate them in https://postgrest.org/en/v12/references/errors.html#group-3-jwt? I.e. give them our own PGRST error code.

### LINKED ISSUE #3926: Throw better error message when empty JWT is sent in Auth header
## Problem

The request with empty JWT hits the db and fails with the permission denied error. The empty JWT is also cached when caching enabled.

```bash
$ curl localhost:3000/authors_only -H "Authorization: Bearer "
{"code":"42501","details":null,"hint":null,"message":"permission denied for table authors_only"}

```

This happens because we default to an empty string here:

https://github.com/PostgREST/postgrest/blob/1a287edf7ecd2bf1eeb3bc4d764b845dac45814d/src/PostgREST/Auth.hs#L57-L58

https://github.com/PostgREST/postgrest/blob/1a287edf7ecd2bf1eeb3bc4d764b845dac45814d/src/PostgREST/Auth.hs#L151-L152

## Solution

The JWT should be validated before hitting the db and a better error message should be given to the client.

### PR DESCRIPTION
**Pull request by taimoorzaeem**
BREAKING CHANGE

We were exposing internal errors via `Show`. This commit improves error messages for better user experience.
Closes #3600, closes #3926.

- [x] Implementation
- [x] Tests
- [x] Docs

I'll add docs once this design/change is approved.

### CODE REVIEW

File: src/PostgREST/Auth.hs [hunk 1]
```diff
@@ -54,33 +54,36 @@ import Protolude
...
-      jwtDecodeError (JWT.BadAlgorithm _) = JwtTokenInvalid "JWSError JWSNoSignatures"
-      jwtDecodeError e                    = JwtTokenInvalid $ show e
+      jwtDecodeError (JWT.KeyError _)     = JwtDecodeError "No suitable key or wrong key type"
+      jwtDecodeError (JWT.BadAlgorithm _) = JwtDecodeError "Wrong or unsupported encoding algorithm"
+      jwtDecodeError (JWT.BadDots dots)   = JwtDecodeError ("Wrong number of '.' periods in JWT: Expected 3, got " <> show dots)
+      jwtDecodeError (JWT.BadHeader _)    = JwtDecodeError "Header couldn't be decoded or contains bad data"
+      jwtDecodeError JWT.BadClaims        = JwtClaimsError "JWT claims couldn't be decoded or contains bad data"
+      jwtDecodeError JWT.BadSignature     = JwtDecodeError "The JWT signature couldn't be decoded or is invalid"
+      jwtDecodeError JWT.BadCrypto        = JwtDecodeError "Cryptographic operation while decoding failed"
+      jwtDecodeError (JWT.Base64Error _)  = JwtDecodeError "A base64 decoding error has occured"
```
[the remark this answers is not in the document]
Comment (steve-chavez) [reply src/PostgREST/Auth.hs:74]: Thinking more about it, maybe some of these error messages can be more generic? Some of them look too technical for API users.

[the remark this answers is not in the document]
Comment (laurenceisla) [reply src/PostgREST/Auth.hs:74]: > Some of them look too technical for API users.

Specially the "Cryptographic..." error, since it also happens when the JWS is invalid. Kinda scary for the user to get that message when the JWT structure is not correct. To take another example, note that we do not raise the [`JWT.BadDots` error ](https://github.com/search?q=repo%3Atekul%2Fjose-jwt+BadDots&type=code) anywhere since we don't use the `decodeClaims` function from the library afaict, so I wouldn't bother in giving it a custom message.

>  Not sure yet, I think we would need some tests to see under what scenarios each one happen.

Yes, all in all, we need to check where are the errors raised in our context and add the message accordingly. Our tests should help in pinpointing them.

[the remark this answers is not in the document]
Comment (taimoorzaeem) [reply src/PostgREST/Auth.hs:74]: > Some of them look too technical for API users

That's exactly why I posed this question in the comment
```haskell
-- should we validate JWT ourselves before decoding or let the library (not very user friendly with errors) handle it?
```

The library errors are just not very user friendly. So maybe let's validate them ourselves so we can give better and precise error messages. But yeah, we need tests before we can decide further.

> Yes, all in all, we need to check where are the errors raised in our context and add the message accordingly. Our tests should help in pinpointing them

Agreed.

File: src/PostgREST/Auth.hs [hunk 2]
```diff
@@ -54,33 +55,48 @@ import Protolude
...
-      -- TODO: Improve errors, those were just taken as-is from hs-jose to avoid
-      -- breaking changes.
+      hasThreeParts :: ByteString -> Either Error ByteString
+      hasThreeParts token = case length $ BS.split (BS.c2w '.') token of
+        3 -> Right token
+        n -> Left $ JwtErr $ JwtDecodeError ("Expected 3 parts in JWT; got " <> show n)
+      hasMin32Chars :: ByteString -> Either Error ByteString
+      hasMin32Chars token
+          | BS.length token >= 32 = Right token
+          | otherwise = Left $ JwtErr $ JwtDecodeError "JWT must be at least 32 characters"
```
Comment (steve-chavez) [inline src/PostgREST/Auth.hs:77]: Wasn't the `jwt-secret` the one that needed to be at least 32 chars? Not the JWT that's sent per request?

Comment (taimoorzaeem) [reply src/PostgREST/Auth.hs:77]: Hmm, now that I think of it, it is unnecessary. I just thought it would be a little nice to give this error, I'll remove it.

File: test/spec/Feature/Auth/JwtCacheSpec.hs [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+  it "denies access to tables that anonymous does not own" $
+    get "/authors_only" `shouldRespondWith`
+      [json| {
+        "hint":null,
+        "details":null,
+        "code":"42501",
+        "message":"permission denied for table authors_only"} |]
+      { matchStatus = 401
+      , matchHeaders = ["WWW-Authenticate" <:> "Bearer"]
+      }
```
Comment (steve-chavez) [inline test/spec/Feature/Auth/JwtCacheSpec.hs:22]: PR looks great overall :+1: 

However this test puzzles me, why is it needed here? Isn't this the same as:

https://github.com/PostgREST/postgrest/blob/4348cb205738a8497fadcaed4ab6015aa465b87d/test/spec/Feature/Auth/AuthSpec.hs#L17-L26

Comment (taimoorzaeem) [reply test/spec/Feature/Auth/JwtCacheSpec.hs:22]: Yes, it's the same but written for code-coverage with `jwt cache: enabled` and `server-timing: enabled|disabled`. I should better mention this in the comments.

Comment (steve-chavez) [reply test/spec/Feature/Auth/JwtCacheSpec.hs:26]: And the rest of the tests related to the JWT cache are io tests in python right? Maybe mention that in the comments. Also, for consistency why not make this an io test? Otherwise you have two files to look at for jwt cache tests.

Comment (taimoorzaeem) [reply test/spec/Feature/Auth/JwtCacheSpec.hs:26]: > Also, for consistency why not make this an io test? Otherwise you have two files to look at for jwt cache tests.

Agreed. I was thinking the same.

**Review by steve-chavez — APPROVED** [review]
