### PR TITLE
fix: jwt error return status 400 for invalid role

### LINKED ISSUE #3601: Return 401 for JWT with invalid role
A JWT with a role that doesn't exist on the server currently returns a `400` status code. Shouldn't this return a `401` as well, just like all the other JWT errors?

https://github.com/PostgREST/postgrest/blob/465170c7d6c51dace3faf68fbb4040353d5571c0/test/io/test_io.py#L84-L88

### PR DESCRIPTION
**Pull request by taimoorzaeem**
Closes #3601.

### CODE REVIEW

File: src/PostgREST/Error.hs [hunk 1]
```diff
@@ -595,6 +595,10 @@ pgErrorStatus authed (SQL.SessionUsageError (SQL.QueryError _ _ (SQL.ResultError
           if BS.isSuffixOf "requires a WHERE clause" m
             then HTTP.status400 -- special case for pg-safeupdate, which we consider as client error
             else HTTP.status500 -- generic function or view server error, e.g. "more than one row returned by a subquery used as an expression"
+        "22023"   -> -- invalid_parameter_value
+          if BS.isPrefixOf "role" m && BS.isSuffixOf "does not exist" m
```
Comment (steve-chavez) [inline src/PostgREST/Error.hs:599]: LGTM :+1: . Checking for the error message should narrow `invalid_parameter_value` cases to just this one.

File: src/PostgREST/Error.hs [hunk 2]
```diff
@@ -595,6 +595,10 @@ pgErrorStatus authed (SQL.SessionUsageError (SQL.QueryError _ _ (SQL.ResultError
           if BS.isSuffixOf "requires a WHERE clause" m
             then HTTP.status400 -- special case for pg-safeupdate, which we consider as client error
             else HTTP.status500 -- generic function or view server error, e.g. "more than one row returned by a subquery used as an expression"
+        "22023"   -> -- invalid_parameter_value
```
Comment (steve-chavez) [inline src/PostgREST/Error.hs:598]: Inlining the reason for better readability
```suggestion
        "22023"   -> -- invalid_parameter_value. Catch nonexistent role error, see https://github.com/PostgREST/postgrest/issues/3601
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -5,6 +5,10 @@ This project adheres to [Semantic Versioning](http://semver.org/).
 
 ## Unreleased
 
+### Fixed
+
+- #3601, Fix jwt error return status `400` for invalid role - @taimoorzaeem
```
Comment (steve-chavez) [inline CHANGELOG.md:10]: I'll try changing to this format from now on, to reduce editing effort on release notes ([ref](https://github.com/PostgREST/postgrest/pull/4020#issuecomment-2868219975)).

```suggestion
- Fix jwt error returning HTTP status `400` for invalid role by @taimoorzaeem in #3601
```
