### PR TITLE
fix: Dump media handlers and timezones with --dump-schema

### LINKED ISSUE #3237: `--dump-schema` does not dump media handlers
### Environment

* PostgreSQL version: 16
* PostgREST version: 12.1 (development)
* Operating system: Linux

### Description of issue

While trying to debug another possible regression in the current development version, I wanted to see the media handlers via `--dump-schema`.

(Edit: The following commands only work after 4a796e0)

Running `postgrest-with-postgresql-16 -f test/spec/fixtures/load.sql postgrest-run` responds with:

```
...
Schema cache loaded 264 Relations, 221 Relationships, 141 Functions, 15 Domain Representations, 45 Media Type Handlers
```

Nice!

But, `postgrest-with-postgresql-16 -f test/spec/fixtures/load.sql postgrest-run --dump-schema | jq '.dbMediaHandlers'` then gives me:

```
[]
```

Something is broken there.

In fact, counting the array items of the json response:

```
{
  "dbMediaHandlers": 0,
  "dbRelationships": 221,
  "dbRepresentations": 15,
  "dbRoutines": 141,
  "dbTables": 264,
  "dbTimezones": 0
}
```

Not sure if timezones is broken as well?

### PR DESCRIPTION
**Pull request by wolfgangwalther**
Those were left out of the schema dump when the features were introduced, probably because ByteString doesn't have a toJSON instance. Changing the type to Text solves this easily.

Resolves #3237

### CODE REVIEW

File: src/PostgREST/MediaType.hs [hunk 1]
```diff
@@ -28,23 +30,23 @@ data MediaType
...
 data MTVndPlanOption
   = PlanAnalyze | PlanVerbose | PlanSettings | PlanBuffers | PlanWAL
-  deriving (Eq, Show, Generic)
+  deriving (Eq, Show, Generic, JSON.ToJSON)
 instance Hashable MTVndPlanOption
 
 data MTVndPlanFormat
   = PlanJSON | PlanText
-  deriving (Eq, Show, Generic)
+  deriving (Eq, Show, Generic, JSON.ToJSON)
```
Comment (steve-chavez) [inline src/PostgREST/MediaType.hs:49]: How about a test on `test/io/test_cli.py` to clear these codecov warnings

File: test/io/test_cli.py [hunk 2]
```diff
@@ -225,3 +235,12 @@ def test_invalid_openapi_mode(invalidopenapimodes, defaultenv):
         for line in dump.split("\n"):
             if line.startswith("openapi-mode"):
                 print(line)
+
+
+# If this test is failing, run pytest with --snapshot-update.
+def test_schema_cache_snapshot(baseenv, snapshot_yaml):
+    "Dump of schema cache should match snapshot."
+
+    schema_cache = yaml.load(cli(["--dump-schema"], env=baseenv), Loader=yaml.Loader)
```
Comment (steve-chavez) [inline test/io/test_cli.py:244]: This converts the JSON to YAML right?

File: src/PostgREST/MediaType.hs (hunk 1 above)
Comment (steve-chavez) [reply src/PostgREST/MediaType.hs:49]: Hm, maybe it's because there are no media handlers on `test/io/fixtures.sql`?

Comment (steve-chavez) [reply src/PostgREST/MediaType.hs:49]: Checking how it can be refactored so this test works..
