### PR TITLE
Expose PKs from all tables in a view

### LINKED ISSUE #2458: v10: Primary Key detection in views with multiple base relations fails
### Environment

* PostgreSQL version: 14.5
* PostgREST version: v10.0.0

### Description of issue

As mentioned in https://github.com/PostgREST/postgrest/pull/2357#issuecomment-1198936055, there's something wrong with detection of primary keys in views.

Here's a test case:

```sql
CREATE TABLE t1 (pk1 INT PRIMARY KEY);
CREATE TABLE t2 (pk2 INT PRIMARY KEY);
CREATE VIEW v AS
SELECT * FROM t1, t2;
```

With v9 it returns in the OpenAPI output:

```json
    "v": {
      "properties": {
        "pk1": {
          "description": "Note:\nThis is a Primary Key.<pk/>",
          "format": "integer",
          "type": "integer"
        },
        "pk2": {
          "description": "Note:\nThis is a Primary Key.<pk/>",
          "format": "integer",
          "type": "integer"
        }
      },
      "type": "object"
    }
```

With v10:

```json
    "v": {
      "properties": {
        "pk1": {
          "description": "Note:\nThis is a Primary Key.<pk/>",
          "format": "integer",
          "type": "integer"
        },
        "pk2": {
          "format": "integer",
          "type": "integer"
        }
      },
      "type": "object"
    }
```

At the same time, the following cURL request:

```bash
curl -H "Prefer: return=headers-only" http://localhost:3000/v -H "Content-Type: application/json" -d '{"pk1":1,"pk2":1}' -v
```

Returns with v9:

```curl
> POST /v HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.84.0
> Accept: */*
> Content-Type: application/json
> Prefer: return=headers-only
> Content-Length: 17
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Transfer-Encoding: chunked
< Date: Wed, 31 Aug 2022 16:30:17 GMT
< Server: postgrest/9.0.1
< Location: /v?pk1=eq.1&pk2=eq.1
< Content-Range: */*
```

But with v10:

```curl
> POST /v HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.84.0
> Accept: */*
> Content-Type: application/json
> Prefer: return=headers-only
> Content-Length: 17
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Transfer-Encoding: chunked
< Date: Wed, 31 Aug 2022 16:37:08 GMT
< Server: postgrest/10.0.0
< Location: /v?pk1=eq.1
< Content-Range: */*
```

Note the wrong `Location` header in the v10 output.

### PR DESCRIPTION
**Pull request by wolfgangwalther**
This is based on #2520. Fixes #2458.

### CODE REVIEW

File: test/spec/fixtures/privileges.sql [hunk 1]
```diff
@@ -1,221 +1,34 @@
...
-    , second_1
-    , fee
-    , baz
-    , janedoe
-    , johnsmith
+    , v1
+    , v2
 TO postgrest_test_anonymous;
 
+REVOKE ALL PRIVILEGES ON TABLE
```
Comment (steve-chavez) [inline test/spec/fixtures/privileges.sql:26]: I like this change but seems there are some tables missing.

On the explicit GRANT list above there were `197` tables.

And on the test schema we have

```
$ postgrest-with-postgresql-14 psql

select count(*) from information_schema.tables where table_schema = 'test';
 count
-------
   220
```

So I guess there are 20 tables missing from the REVOKE list?

Comment (steve-chavez) [reply test/spec/fixtures/privileges.sql:26]: `insertonly` for example is missing.

```
select count(*)
from information_schema.tables
where table_schema = 'test' and table_name not in (
     'items'
    ,'items2'
    ,'items3'
    ,'articleStars'
    ,'articles'
    ,'arrays'
    ,'auto_incrementing_pk'
    ,'clients'
    ,'comments'
    ,'complex_items'
    ,'compound_pk'
    ,'compound_pk_view'
    ,'deferrable_unique_constraint'
    ,'empty_table'
    ,'fav_numbers'
    ,'has_count_column'
    ,'has_fk'
    ,'insertable_view_with_join'
    ,'json_table'
    ,'materialized_view'
    ,'menagerie'
    ,'no_pk'
    ,'nullable_integer'
    ,'projects'
    ,'projects_view'
    ,'projects_view_alt'
    ,'test_null_pk_competitors_sponsors'
    ,'simple_pk'
    ,'simple_pk2'
    ,'tasks'
    ,'filtered_tasks'
    ,'tsearch'
    ,'users'
    ,'users_projects'
    ,'users_tasks'
    ,'files'
    ,'touched_files'
    ,'Escap3e;'
    ,'ghostBusters'
    ,'withUnique'
    ,'clashing_column'
    ,'موارد'
    ,'addresses'
    ,'orders'
    ,'consumers_view'
    ,'consumers_view_view'
    ,'consumers_extra_view'
    ,'orders_view'
    ,'images'
    ,'images_base64'
    ,'w_or_wo_comma_names'
    ,'items_with_different_col_types'
    ,'entities'
    ,'child_entities'
    ,'grandchild_entities'
    ,'ranges'
    ,'being'
    ,'descendant'
    ,'being_part'
    ,'part'
    ,'leak'
    ,'perf_articles'
    ,'employees'
    ,'tiobe_pls'
    ,'single_unique'
    ,'compound_unique'
    ,'only_pk'
    ,'family_tree'
    ,'managers'
    ,'organizations'
    ,'authors'
    ,'publishers'
    ,'books'
    ,'forties_books'
    ,'fifties_books'
    ,'sixties_books'
    ,'person'
    ,'message'
    ,'person_detail'
    ,'space'
    ,'zone'
    ,'projects_dump'
    ,'UnitTest'
    ,'json_arr'
    ,'jsonb_test'
    ,'authors_books_number'
    ,'authors_have_book_in_decade'
    ,'authors_have_book_in_decade2'
    ,'forties_and_fifties_books'
    ,'odd_years_publications'
    ,'foos'
    ,'bars'
    ,'materialized_projects'
    ,'contract'
    ,'player_view'
    ,'contract_view'
    ,'ltree_sample'
    ,'isn_sample'
    ,'projects_count_grouped_by'
    ,'Server Today'
    ,'pgrst_reserved_chars'
    ,'authors_w_entities'
    ,'openapi_types'
    ,'openapi_defaults'
    ,'getallprojects_view'
    ,'get_projects_above_view'
    ,'web_content'
    ,'pages'
    ,'referrals'
    ,'big_projects'
    ,'sites'
    ,'jobs'
    ,'main_jobs'
    ,'whatev_projects'
    ,'whatev_sites'
    ,'whatev_jobs'
    ,'agents'
    ,'departments'
    ,'schedules'
    ,'activities'
    ,'unit_workdays'
    ,'unit_workdays_fst_shift'
    ,'stuff'
    ,'loc_test'
    ,'v1.parents'
    ,'v2.parents'
    ,'v2.another_table'
    ,'v1.children'
    ,'v2.children'
    ,'screens'
    ,'labels'
    ,'label_screen'
    ,'actors'
    ,'films'
    ,'personnages'
    ,'end_1'
    ,'end_2'
    ,'schauspieler'
    ,'filme'
    ,'rollen'
    ,'products'
    ,'suppliers'
    ,'products_suppliers'
    ,'trade_unions'
    ,'suppliers_trade_unions'
    ,'client'
    ,'clientinfo'
    ,'contact'
    ,'chores'
    ,'limited_update_items'
    ,'limited_update_items_cpk'
    ,'limited_update_items_no_pk'
    ,'limited_update_items_view'
    ,'limited_update_items_wnonuniq_view'
    ,'limited_delete_items'
    ,'limited_delete_items_cpk'
    ,'limited_delete_items_no_pk'
    ,'limited_delete_items_view'
    ,'plate'
    ,'well'
    ,'limited_delete_items_wnonuniq_view'
    ,'limited_delete_items_cpk_view'
    ,'limited_update_items_cpk_view'
    ,'xmltest'
    ,'oid_test'
    ,'job'
    ,'series'
    ,'adaptation_notifications'
    ,'series_popularity'
    ,'test'
    ,'view_test'
    ,'shops'
    ,'shop_bles'
    ,'do$llar$s'
    ,'safe_update_items'
    ,'safe_delete_items'
    ,'unsafe_update_items'
    ,'unsafe_delete_items'
    ,'videogames'
    ,'designers'
    ,'students'
    ,'students_info'
    ,'students_view'
    ,'students_info_view'
    ,'country'
    ,'capital'
    ,'first'
    ,'second'
    ,'first_1'
    ,'second_1'
    ,'fee'
    ,'baz'
    ,'janedoe'
    ,'johnsmith'
);

 count
-------
    34

```

Removed from the list:
```
    , public.public_consumers
    , public.public_orders
    , "SPECIAL ""@/\#~_-".languages
    , "SPECIAL ""@/\#~_-".names
```

Comment (steve-chavez) [reply test/spec/fixtures/privileges.sql:26]: These are missing

```
 private_table
 sponsors
 competitors
 bar
 Foo
 projects_auto_updatable_view_without_pk
 projects_auto_updatable_view_with_pk
 projects_view_without_triggers
 projects_view_with_all_triggers_with_pk
 projects_view_with_all_triggers_without_pk
 projects_view_with_insert_trigger
 projects_view_with_update_trigger
 projects_view_with_delete_trigger
 car_models
 car_models_2021
 car_models_default
 car_brands
 car_model_sales_202101
 car_model_sales
 car_model_sales_default
 car_racers
 car_dealers
 car_dealers_springfield
 car_dealers_default
 car_models_car_dealers
 xml
 no_pk_view
 plate_plan_step
 insertonly
 car_models_car_dealers_10to20
 car_models_car_dealers_default
```

**Review by steve-chavez — APPROVED** [review]
