### PR TITLE
fix: regression with parameter charset=utf-8 in mediatype

### LINKED ISSUE #4030: Content-Type not acceptable error with "charset=utf-8"
### Environment

* PostgreSQL version: 17
* PostgREST version: v12.2.10
* Operating system: Official docker image

### Description of issue

Requests in v12.2.10 that have a charset in the Content-Type header, eg:
```
"Content-Type": "application/json; charset=utf-8"
```

Are failing with the following error:
> Content-Type not acceptable: application/json; charset=utf-8

Requests without the charset are successful, eg;
```
"Content-Type": "application/json"
```

This seems to have been introduced after v12.2.8 as the same request is successful in that version.

### PR DESCRIPTION
**Pull request by taimoorzaeem**
Closes #4030.

### CODE REVIEW

File: src/PostgREST/MediaType.hs [hunk 1]
```diff
@@ -198,12 +198,14 @@ tokenizeMediaType = do
...
             P.spaces
             P.char '='
             P.spaces
             val <- P.try pQuoted <|> P.try pUnQuoted
             return (T.pack key, T.pack val)
               where
-                pUnQuoted = P.many1 (P.alphaNum <|> P.oneOf "|")
+                pUnQuoted = P.many1 (P.alphaNum <|> P.oneOf specialChars)
                 pQuoted = P.char '\"' *> P.manyTill P.anyChar (P.char '\"')
+                -- allowed chars as per RFC 2045
```
Comment (steve-chavez) [inline src/PostgREST/MediaType.hs:210]:
```suggestion
                -- allowed chars as per RFC 2045 https://datatracker.ietf.org/doc/html/rfc2045#section-5.1
```

File: test/spec/Feature/Query/CustomMediaSpec.hs [hunk 2]
```diff
@@ -382,3 +382,26 @@ spec = describe "custom media types" $ do
...
+        [json|{"val":1}|]
+        { matchStatus = 200
+        , matchHeaders = ["Content-Type" <:> "application/json; charset=utf-8"]
+        }
+
+    it "allows special chars as specified in RFC 2045 in the key and value of parameter" $
+      request methodPost "/rpc/overloaded_default"
+                                        --        key         =     value
+                                        --   ----------------- -----------------
+        [("Content-Type", "application/json; !#$%^&*-_+/'.{}~`=!#$%^&*-_+/'.{}~`")]
```
Comment (steve-chavez) [inline test/spec/Feature/Query/CustomMediaSpec.hs:401]: If the key values are unknown, should we respond with an error? Or should we be lenient? Anything on the RFC about this?

Comment (steve-chavez) [reply test/spec/Feature/Query/CustomMediaSpec.hs:401]: Not that anything should be changed now, but we could leave it as TODO or issue.. being too strict might break other clients.

Comment (taimoorzaeem) [reply test/spec/Feature/Query/CustomMediaSpec.hs:401]: > Or should we be lenient? Anything on the RFC about this?

RFC says:
> MIME implementations must ignore any parameters whose names they do not recognize.

Thanks for pointing the leniency out. I actually wrote it to be lenient. The actual mistake was this:
```haskell
P.eof
```
After failing and backtracking, it looked for `EOF` and then failed. So, removing this one line should fix this issue entirely.

**Review by steve-chavez — APPROVED** [review]
