### PR TITLE
fix: replace json parser error with generic msg

### LINKED ISSUE #2344: Better error message for `{"message":"Error in $: not enough input"}`
When doing:

```bash
http POST 'localhost:3000/projects' <<JSON

JSON
```

The response is:

```bash
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Tue, 21 Jun 2022 18:54:50 GMT
Server: postgrest/9.0.0.20220531 (pre-release) (fe8b32d)
Transfer-Encoding: chunked

{
    "code": "PGRST102",
    "details": null,
    "hint": null,
    "message": "Error in $: not enough input"
}
```

It'd be better to reply with a generic `Empty or invalid json`.

### PR DESCRIPTION
**Pull request by develop7**
Drops Aeson's parser error from the output in favor of a generic message, per the suggestion in #2344.

Fixes #2344

### CODE REVIEW

File: test/spec/Feature/Query/QuerySpec.hs [hunk 1]
```diff
@@ -28,6 +28,19 @@ spec actualPgVersion = do
     it "causes a 404" $
       get "/faketable" `shouldRespondWith` 404
 
+  describe "Sending malformed json" $ do
+    it "causes a 400" $ do
+      post "/items" "}{ x" `shouldRespondWith`
+        [json|{"message":"Empty or invalid json","code":"PGRST102","details":null,"hint":null}|]
+        { matchStatus  = 400
+        , matchHeaders = [matchContentTypeJson]
+        }
```
Comment (laurenceisla) [inline test/spec/Feature/Query/QuerySpec.hs:37]: The `QuerySpec.hs` seems to test only `get` requests. I think it's OK to leave it as you did before, both on Insert and Update Specs.

Comment (develop7) [reply test/spec/Feature/Query/QuerySpec.hs]: Got it, thank you

**Comment by laurenceisla** [comment]
LGTM or is there anything else missing? Don't forget to add the CHANGELOG.

**Comment by develop7** [comment]
> Don't forget to add the CHANGELOG.

Whoops, done. Thanks for the heads-up.

> is there anything else missing?

No, not really

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,6 +8,8 @@ This project adheres to [Semantic Versioning](http://semver.org/).
 ### Fixed
 
  - #3054, Fix not allowing special characters in JSON keys - @laurenceisla
+ - #3090, Replace JSON parser error with generic message - @develop7
+   + Fixes #2344
```
Comment (laurenceisla) [inline CHANGELOG.md:12]:
```suggestion
 - #2344, Replace JSON parser error with a clearer generic message - @develop7
```

Usually we link the issue directly and not the PR, unless there's no issue or the PR solves a lot of them

**Review by laurenceisla — APPROVED** [review]
