### PR TITLE
Fix: Returning 204 No Content where appropriate

### LINKED ISSUE #2001: Inconsistent return values for functions returning void
### Environment

* PostgreSQL version: 12.8
* PostgREST version: 8.0.0
* Operating system: Ubuntu 20.04

### Description of issue

Expected behavior: When calling functions declared returning void, postgrest returns a consistent value reflecting this (preferrably `204 No Content`).

Actual behavior: postgrest returns a empty string or null, depending on the language of the function.

### Example

```
CREATE FUNCTION x() RETURNS VOID AS $$ BEGIN
END $$ LANGUAGE plpgsql;
CREATE FUNCTION z() RETURNS VOID AS $$ $$ LANGUAGE sql;
```

For the first function, postgrest returns `""`:

```
GET /rpc/x HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3



HTTP/1.1 200 OK
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Oct 2021 19:48:17 GMT
Server: postgrest/8.0.0
Transfer-Encoding: chunked

""
```

For the sql function, postgrest returns `null`:

```
GET /rpc/z HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3



HTTP/1.1 200 OK
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Oct 2021 19:49:38 GMT
Server: postgrest/8.0.0
Transfer-Encoding: chunked

null
```

### Proposal

Postgrest should return `204 No Content` as result for functions that return void. (This also was suggested in #1762, but not implemented.)

### PR DESCRIPTION
**Pull request by wolfgangwalther**
While trying to fix #2001, I started with making our expectance for a absent or present `Content-Type` header more explicit in the spec tests. While doing that, I noticed that a `PUT` was inconsistently returning a `Content-Type` when returning with `204 No Content`.

The first commit improves those tests and fixes PUT.

The second commit solves a TODO in a related part of the code - it should be self-explanatory.

The third commit then implements the breaking change to return `204 No Content` without body for `VOID` RPCs.

I consider only the part about RPCs a breaking change and am thinking about merging the other fix ahead of time. I'd like us to be able to get a bugfix release out, once we fix a couple of the open, non-breaking bugs, so I'd like to hold back on merging the breaking change for now.

### CODE REVIEW

File: test/Feature/IgnorePrivOpenApiSpec.hs [hunk 1]
```diff
@@ -19,8 +19,14 @@ spec :: SpecWith ((), Application)
 spec = describe "OpenAPI Ignore Privileges" $ do
   it "root path returns a valid openapi spec" $ do
     validateOpenApiResponse [("Accept", "application/openapi+json")]
-    request methodHead "/" (acceptHdrs "application/openapi+json") ""
-      `shouldRespondWith` "" { matchStatus  = 200 }
+    request methodHead "/"
+        (acceptHdrs "application/openapi+json")
+        ""
```
Comment (steve-chavez) [inline test/Feature/IgnorePrivOpenApiSpec.hs:24]: This one is just reformatting right?

File: test/Feature/RangeSpec.hs [hunk 2]
```diff
@@ -109,11 +109,10 @@ spec = do
...
           request methodGet "/menagerie"
-                  [("Prefer", "count=none")] ""
-            `shouldRespondWith` "[]"
-            { matchStatus  = 200
-            , matchHeaders = ["Content-Range" <:> "*/*"]
-            }
+              [("Prefer", "count=none")] ""
+            `shouldRespondWith`
+              [json|[]|]
+              { matchHeaders = ["Content-Range" <:> "*/*"] }
```
Comment (steve-chavez) [inline test/Feature/RangeSpec.hs:115]: Hm, why does 200 go away here?

**Comment by steve-chavez** [comment]
> The second commit solves a TODO in a related part of the code - it should be self-explanatory.

Nice one, that TODO was there ever since I can remember.

> I'd like us to be able to get a bugfix release out, once we fix a couple of the open, non-breaking bugs, so I'd like to hold back on merging the breaking change for now.

Cool, I agree. With that it should be good to merge.
