### PR TITLE
fix: Add errors OpenAPIDisabled and InvalidResourcePath

### LINKED ISSUE #3906: Empty error message in some code paths
One last concern, we are still using `NotFound` error in a couple places, which returns an empty error json:

https://github.com/PostgREST/postgrest/blob/e2dd4354d5e462ec9364c6237a43c7be650a9803/src/PostgREST/ApiRequest/Types.hs#L82

https://github.com/PostgREST/postgrest/blob/e2dd4354d5e462ec9364c6237a43c7be650a9803/src/PostgREST/Error.hs#L135

This seems fine for now, but maybe should be improved later (add error msg, details etc) for better UX?

_Originally posted by @taimoorzaeem in https://github.com/PostgREST/postgrest/issues/3869#issuecomment-2611743704_

### PR DESCRIPTION
**Pull request by taimoorzaeem**
Removes the empty `NotFound` error.

Closes #3906.

### CODE REVIEW

File: test/spec/Feature/OpenApi/DisabledOpenApiSpec.hs [hunk 1]
```diff
@@ -3,14 +3,18 @@ module Feature.OpenApi.DisabledOpenApiSpec where
...
 spec :: SpecWith ((), Application)
 spec =
   describe "Disabled OpenApi" $ do
-    it "responds with 404" $
+    it "responds with 400" $
       request methodGet "/"
-        [("Accept","application/openapi+json")] "" `shouldRespondWith` 404
+        [("Accept","application/openapi+json")] ""
+        `shouldRespondWith`
+        [json| {"code":"PGRST126","details":null,"hint":"Enable configuration `openapi-mode`","message":"Open API mode is disabled but API root path is accessed"} |]
```
Comment (steve-chavez) [inline test/spec/Feature/OpenApi/DisabledOpenApiSpec.hs:19]: Since this is a message for an API user, we shouldn't reveal server details.

```suggestion
        [json| {"code":"PGRST126","details":null,"hint": null,"message":"Open API mode is disabled"} |]
```

However the error code section in the docs can mention `openapi-mode`.

File: CHANGELOG.md [hunk 2]
```diff
@@ -17,6 +17,7 @@ This project adheres to [Semantic Versioning](http://semver.org/).
  - #2255, Apply `to_tsvector()` explicitly to the full-text search filtered column (excluding `tsvector` types) - @laurenceisla
  - #1578, Log the main SQL query to stderr at the current `log-level` when `log-query=main-query` - @laurenceisla
  - #3903, Log connection pool borrows on `log-level=debug` - @taimoorzaeem
+ - #3906, Add `PGRST125` and `PGRST126` errors - @taimoorzaeem
```
Comment (steve-chavez) [inline CHANGELOG.md:20]: I think this should be a fix, given the description of https://github.com/PostgREST/postgrest/issues/3906
```suggestion
```

File: docs/references/errors.rst [hunk 3]
```diff
@@ -253,6 +253,14 @@ Related to the HTTP request elements.
 |               |             | See :ref:`db-aggregates-enabled`.                           |
 | PGRST123      |             |                                                             |
 +---------------+-------------+-------------------------------------------------------------+
+| .. _pgrst125: | 400         | Invalid path is specified in request URL.                   |
+|               |             |                                                             |
+| PGRST125      |             |                                                             |
++---------------+-------------+-------------------------------------------------------------+
+| .. _pgrst126: | 400         | Open API config is disabled but API root path is            |
```
Comment (steve-chavez) [inline docs/references/errors.rst:260]: I believe these two should still return status 404.

400 is more for when the resource exists but the client is trying to do something invalid.

File: test/spec/Feature/OpenApi/DisabledOpenApiSpec.hs [hunk 4]
```diff
@@ -3,14 +3,18 @@ module Feature.OpenApi.DisabledOpenApiSpec where
...
 spec :: SpecWith ((), Application)
 spec =
   describe "Disabled OpenApi" $ do
-    it "responds with 404" $
+    it "responds with 400" $
       request methodGet "/"
-        [("Accept","application/openapi+json")] "" `shouldRespondWith` 404
+        [("Accept","application/openapi+json")] ""
+        `shouldRespondWith`
+        [json| {"code":"PGRST126","details":null,"hint":null,"message":"Open API mode is disabled but API root path is accessed"} |]
```
Comment (steve-chavez) [inline test/spec/Feature/OpenApi/DisabledOpenApiSpec.hs:19]: We need a more generic error message, maybe:
```suggestion
        [json| {"code":"PGRST126","details":null,"hint":null,"message":"Root endpoint metadata is disabled"} |]
```

File: test/spec/Feature/Query/QuerySpec.hs [hunk 5]
```diff
@@ -1625,3 +1625,10 @@ spec = do
       get "/infinite_recursion?select=*" `shouldRespondWith`
         [json|{"code":"42P17","message":"infinite recursion detected in rules for relation \"infinite_recursion\"","details":null,"hint":null}|]
         { matchStatus = 500 }
+
+  context "invalid resource path" $ do
+    it "return http status 400" $
+      get "/first/second/third?select=*"
+      `shouldRespondWith`
+      [json| {"code":"PGRST125","details":"Request path: /first/second/third","hint":null,"message":"Invalid path specified in request URL"} |]
```
Comment (steve-chavez) [inline test/spec/Feature/Query/QuerySpec.hs:1633]: Details don't add much, so just:
```suggestion
      [json| {"code":"PGRST125","details":"null,"hint":null,"message":"Invalid path specified in URL"} |]
```

It might bring some simplification in code too.

File: docs/references/errors.rst (hunk 3 above)
Comment (taimoorzaeem) [reply docs/references/errors.rst]: Sure. I have drafted this PR, will open after #3961 is merged to avoid conflicts.

**Review by steve-chavez — APPROVED** [review]

File: CHANGELOG.md [hunk 6]
```diff
@@ -30,6 +30,7 @@ This project adheres to [Semantic Versioning](http://semver.org/).
  - #3697, #3602, Handle queries on non-existing table gracefully - @taimoorzaeem
  - #3600, #3926, Improve JWT errors - @taimoorzaeem
  - #3013, Fix `order=` with POST, PATCH, PUT and DELETE requests - @taimoorzaeem
+ - #3906, Add `PGRST125` and `PGRST126` errors instead of empty json - @taimoorzaeem
```
Comment (steve-chavez) [inline CHANGELOG.md:33]:
```suggestion
```
