### PR TITLE
fix: filtering the returned representation for mutations when using or/and filters

### LINKED ISSUE #3707: Invalid query generated when selecting after updating using or operator
### Environment

* PostgreSQL version: public.ecr.aws/supabase/postgres:15.6.1.113
* PostgREST version: public.ecr.aws/supabase/postgrest:v12.2.3

### Description of issue

I faced a problem when trying to update a timestamp column and return the updated value.

Here is the table structure:
```sql
create table jobs (
    id uuid primary key default gen_random_uuid(),
    started_at timestamp with time zone
)
```
I want to update and return a job if it has not been started yet or if it was started more then one minute ago.

But when I make the following query using supabase:
```ts
const min_start_at = new Date(Date.now() - 60000).toISOString()
supabase.from("jobs").update({ started_at: "now()" })
  .eq("id", id).or(`started_at.is.null,started_at.lt.${min_start_at}`)
  .select("id,started_at").maybeSingle()
```
PostgREST generates a query that doesn't returns the updated row:
```sql
WITH pgrst_source AS (
    UPDATE "public"."jobs"
    SET "started_at" = "pgrst_body"."started_at"
    FROM
        (SELECT $1 AS json_data) pgrst_payload,
        LATERAL (SELECT "started_at" FROM json_to_record(pgrst_payload.json_data) AS _("started_at" timestamp with time zone) ) pgrst_body
    WHERE  "public"."jobs"."id" = $2
        AND  ( "public"."jobs"."started_at" IS NULL OR  "public"."jobs"."started_at" < $3)
    RETURNING "public"."jobs"."id", "public"."jobs"."started_at"
)
SELECT
    '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total,
    array[]::text[] AS header, coalesce(json_agg(_postgrest_t)->0, 'null') AS body,
    nullif(current_setting('response.headers', true), '') AS response_headers,
    nullif(current_setting('response.status', true), '') AS response_status,
    '' AS response_inserted
FROM (
    SELECT "jobs"."started_at"
    FROM "pgrst_source" AS "jobs"
    WHERE  ( "jobs"."started_at" IS NULL OR  "jobs"."started_at" < $4)
);
```
The problem is the last WHERE clause because at this stage `started_at` has already been set to `now()` which can't be less then a moment in the past.

Furthermore, if you try to remove `started_at` from select:
```ts
const min_start_at = new Date(Date.now() - 60000).toISOString()
supabase.from("jobs").update({ started_at: "now()" })
  .eq("id", id).or(`started_at.is.null,started_at.lt.${min_start_at}`)
  .select("id").maybeSingle()
```
you'll recieve an error because the following query is invalid:
```sql
WITH pgrst_source AS (
    UPDATE "public"."jobs"
    SET "started_at" = "pgrst_body"."started_at"
    FROM (
        SELECT $1 AS json_data) pgrst_payload,
        LATERAL (SELECT "started_at" FROM json_to_record(pgrst_payload.json_data) AS _("started_at" timestamp with time zone) ) pgrst_body
    WHERE  "public"."jobs"."id" = $2
        AND  ( "public"."jobs"."started_at" IS NULL OR  "public"."jobs"."started_at" < $3)
    RETURNING "public"."jobs"."id"
)
SELECT
    '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total,
    array[]::text[] AS header, coalesce(json_agg(_postgrest_t)->0, 'null') AS body,
    nullif(current_setting('response.headers', true), '') AS response_headers,
    nullif(current_setting('response.status', true), '') AS response_status,
    '' AS response_inserted
FROM (
    SELECT "jobs"."id"
    FROM "pgrst_source" AS "jobs"
    WHERE  ( "jobs"."started_at" IS NULL OR  "jobs"."started_at" < $4)
);
```
Notice the `pgrst_source` here, it contains only `id` but the WHERE clause still references `started_at`.

Looks like the problem is related to the `or` operator because when I use `is.null`:
```ts
supabase.from("jobs").update({ started_at: "now()" })
  .eq("id", id).is("started_at", null)
  .select("id,started_at").maybeSingle()
```
or `lt.` separately:
```ts
const min_start_at = new Date(Date.now() - 60000).toISOString()
supabase.from("jobs").update({ started_at: "now()" })
  .eq("id", id).lt("started_at", min_start_at)
  .select("id,started_at").maybeSingle()
```
there is no WHERE clause in the generated by PostgREST query:
```sql
WITH pgrst_source AS (
    UPDATE "public"."jobs"
    SET "started_at" = "pgrst_body"."started_at"
    FROM
        (SELECT $1 AS json_data) pgrst_payload,
        LATERAL (SELECT "started_at" FROM json_to_record(pgrst_payload.json_data) AS _("started_at" timestamp with time zone) ) pgrst_body
    WHERE  "public"."jobs"."id" = $2
        AND  "public"."jobs"."started_at" < $3
    RETURNING "public"."jobs"."id", "public"."jobs"."started_at"
)
SELECT
    '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total,
    array[]::text[] AS header, coalesce(json_agg(_postgrest_t)->0, 'null') AS body,
    nullif(current_setting('response.headers', true), '') AS response_headers,
    nullif(current_setting('response.status', true), '') AS response_status,
    '' AS response_inserted
FROM (
    SELECT "jobs"."started_at"
    FROM "pgrst_source" AS "jobs"
);
```
This is expected behavior and `or` operator should not add WHERE clause as I understand.

### PR DESCRIPTION
**Pull request by laurenceisla**
Closes #3707

### CODE REVIEW

File: src/PostgREST/Plan.hs [hunk 1]
```diff
@@ -963,10 +963,16 @@ addRanges ApiRequest{..} rReq =
...
-  foldr addLogicTreeToNode (Right rReq) qsLogic
+  foldr addLogicTreeToNode (Right rReq) logic
   where
     QueryParams.QueryParams{..} = iQueryParams
 
+    logic =
+      case iAction of
+        ActDb (ActRelationRead _  _) -> qsLogic
+        ActDb (ActRoutine _ _)       -> qsLogic
+        _                            -> filter (not . null . fst) qsLogic
```
Comment (steve-chavez) [inline src/PostgREST/Plan.hs:975]: Could you explain this logic with some comments?

I see that the tests are good and solve the issue but I'm lost on the solution :(

Comment (laurenceisla) [reply src/PostgREST/Plan.hs:975]: Added a comment there. Basically, it's the same logic applied to mutation filters: use only the non-root logic filters and apply them to the embeddings on the returned representation.

https://github.com/PostgREST/postgrest/blob/5356f4e973364c3ee39cb042bbc2a63a1c7fe4cb/src/PostgREST/Plan.hs#L824-L828

I didn't create another component like `QueryParams.qsFiltersNotRoot` because I think this won't be used anymore once #2323 is fixed.

Comment (steve-chavez) [reply src/PostgREST/Plan.hs:975]: Thanks, I see it now. I wonder if there's a way to reuse this code for both filters and the logic tree.

Comment (steve-chavez) [reply src/PostgREST/Plan.hs:975]: Checked the code and reusing doesn't seem trivial. So it LGTM.
