### PR TITLE
fix: unnecessary set default_transaction_isolation

### LINKED ISSUE #2959: There's a typo in "default_transation_isolation" with a missing c
https://github.com/PostgREST/postgrest/blob/1b4dae5a7a48842880a7ed11b9a7b6487023e4ad/src/PostgREST/Config/Database.hs#L157

### PR DESCRIPTION
**Pull request by steve-chavez**
Closes #2959

### CODE REVIEW

File: src/PostgREST/Config/Database.hs [hunk 1]
```diff
@@ -154,7 +154,7 @@ queryRoleSettings prepared =
       select
         kv.rolname,
         i.value as iso_lvl,
-        array_agg(row(kv.key, kv.value)) filter (where key <> 'default_transation_isolation') as role_settings
+        coalesce(array_agg(row(kv.key, kv.value)) filter (where key <> 'default_transaction_isolation'), '{}') as role_settings
```
Comment (steve-chavez) [inline src/PostgREST/Config/Database.hs:157]: I tried putting the `'default_transaction_isolation'` into a variable and interpolate with `qc` - this fails to compile.

This has happened a number of times now, we need a new quasiquoting lib.
