### PR TITLE
fix: Restore showing  LISTEN pgrst in pg_stat_activity

### LINKED ISSUE #4857: Querying `pg_stat_activity` no longer shows the `LISTEN pgrst;` command
### Environment

* PostgreSQL version: 17.9
* PostgREST version: 14.9 onwards
* Operating system: MacOS 15

### Description of issue

We could check the `pid` of the listener in the `pg_stat_activity` view, like so:

```sql
select pid, query from pg_stat_activity 
where application_name ilike '%postgrest%' and query ilike '%listen%';
```
```
  pid  |     query
-------+----------------
 86265 | LISTEN "pgrst"
(1 row)
```

Now, It doesn't show anything. Removing the filter shows this:

```
  pid  |                                                query
-------+----------------------------------------------------------------------------------------------------
 86682 | SELECT current_setting('server_version_num')::integer, current_setting('server_version'), version()
```

It starts in b9c8562641321b1ce0a2c47d32e5a2de6615fe62, in these lines: 

https://github.com/PostgREST/postgrest/blob/ea08a4d767676fa1e62c1d456cc5afa7a3d3430f/src/PostgREST/Listener.hs#L71-L73

Moving the listener to the end seems to solve this, but  I'mnot sure if failing with version selection first would be OK here (in case of any DB failures).

### PR DESCRIPTION
**Pull request by mkleczek**
**DISCLAIMER:**
This commit was authored entirely by a human without the assistance of LLMs.

Fixes #4857

Stacked on top of #4860 to enable testing.

### CODE REVIEW

File: test/observability/Observation/ListenerSpec.hs [hunk 1]
```diff
@@ -26,6 +33,19 @@ spec = describe "Listener tests" $ do
...
+
+    liftIO $ withListener appState $ do
+      waitFor (1 * sec) "DBListenStart" $ \x -> [ o | o@(DBListenStart {}) <- pure x ]
+      AppState.usePool appState
+        (SQL.statement ()
+          (SQL.Statement "SELECT query FROM pg_stat_activity WHERE usename = current_user"
+            HE.noParams
+            (HD.rowList (HD.column $ HD.nonNullable HD.text)) True))
+        >>= either (expectationFailure . show) (`shouldContain` ["LISTEN \"pgrst\""])
+
```
Comment (wolfgangwalther) [inline test/observability/Observation/ListenerSpec.hs]: I guess my comment in https://github.com/PostgREST/postgrest/pull/4860#issuecomment-4341788552 applies here:

Is it a requirement to test this in hspec, why not in the IO tests?

File: CHANGELOG.md [hunk 2]
```diff
@@ -20,6 +20,7 @@ All notable changes to this project will be documented in this file. From versio
 - Shutdown should wait for in flight requests by @mkleczek in #4702
 - Fix login with uppercase and mixed case role names by @taimoorzaeem in #4678
 - Remove automatic transaction retries on `40001 (serialization_failure)` errors to prevent replication lag by @laurenceisla in #3673
+- Show LISTEN pgrst in pg_stat_activity by @mkleczek in #4857 #4859
```
Comment (wolfgangwalther) [inline CHANGELOG.md]: As a user, I could not care less. I don't think this is important to them. Also, this is not really a thing we're promising to the user.

I'd consider this kind of change + test just a part of #4643, right?

Comment (mkleczek) [reply CHANGELOG.md]: > As a user, I could not care less. I don't think this is important to them. Also, this is not really a thing we're promising to the user.
> 
> I'd consider this kind of change + test just a part of #4643, right?

No, this is a fix of #4857 - it seems we **do** promise it. https://www.hyrumslaw.com

Comment (wolfgangwalther) [reply CHANGELOG.md]: I don't think the fact that Laurence created an issue about my observation that this is not displayed anymore makes this something that we should support as a feature on its own.

Comment (mkleczek) [reply CHANGELOG.md]: > I don't think the fact that Laurence created an issue about my observation that this is not displayed anymore makes this something that we should support as a feature on its own.

Not sure about that. @steve-chavez would like to revert some features we already merged because of that. Hence the fix.

Comment (steve-chavez) [reply CHANGELOG.md]: > As a user, I could not care less. I don't think this is important to them. Also, this is not really a thing we're promising to the user.

@wolfgangwalther There's another type of user I put in this [diagram on the docs](https://docs.postgrest.org/en/v14/explanations/architecture.html#bird-s-eye-view), I called it the "operator" but maybe there are more apt names like "administrator". (I also intended it to point to the db in the diagram, but it came out all crossed). It's expected to monitor the health of PostgREST (and when you do it you have to look at the database queries as well, for things like locked transactions or zombie LISTEN processes).  

So https://github.com/PostgREST/postgrest/issues/4857 is a bug in the same way https://github.com/PostgREST/postgrest/issues/4751#issuecomment-4157621559 was (and https://github.com/PostgREST/postgrest/issues/4821 follows a similar logic), it's a "deficiency in observability" . PostgREST queries are expected to have a certain shape and so far we have been pretty stable in this regard, since we even have tests:

https://github.com/PostgREST/postgrest/blob/ea08a4d767676fa1e62c1d456cc5afa7a3d3430f/test/spec/Feature/Query/PlanSpec.hs#L244

For this case we should test a basic shape of the LISTENer queries and maybe reword the CHANGELOG.

Comment (steve-chavez) [reply CHANGELOG.md]: I think we should agree that some query shape (maybe just the start of a query and wrapping CTEs) should be maintained in minor versions. That does fit with our "no new features" in minor stance. Thoughts?

File: test/observability/Observation/ListenerSpec.hs (hunk 1 above)
Comment (steve-chavez) [reply test/observability/Observation/ListenerSpec.hs]: Yeah I don't see why https://github.com/PostgREST/postgrest/pull/4859/changes/a191f8dc17c5999c822d6879d2c6fc2dc83892bf has to be included here too. It should be enough to query `pg_stat_activity` in the io tests? You could do it with a wrapping RPC. We did that for checking prepared statements for example:

https://github.com/PostgREST/postgrest/blob/ea08a4d767676fa1e62c1d456cc5afa7a3d3430f/test/io/test_io.py#L421-L439

File: CHANGELOG.md (hunk 2 above)
Comment (wolfgangwalther) [reply CHANGELOG.md]: Thanks for clarifying that this was indeed labeled a bug/fix very intentionally. I still disagree, though ;)

> I think we should agree that some query shape (maybe just the start of a query and wrapping CTEs) should be maintained in minor versions.

I really think we should not guarantee any of that. The actual queries we are running are really an implementation detail, nothing else. We should **not** guarantee their shape *just because of observability*.

TLDR: If you really need a way to identify PostgREST sessions, take the ability to freely change application_name away and force it. Don't let anyone identify PostgREST via its queries. That's just wrong.

Edit: Forgot an important *not* above...

Comment (steve-chavez) [reply CHANGELOG.md]: > TLDR: If you really need a way to identify PostgREST sessions, take the ability to freely change application_name away and force it.

That's the problem though. Right now there's no way to differentiate between pool sessions and the LISTEN session. Because we share the same connection uri for both, if you override `application_name` that wouldn't allow you to pinpoint the LISTEN session (and the connection pool size can be big); all you're left with is the `LISTEN` query (which is lost as per https://github.com/PostgREST/postgrest/issues/4857). I haven't been able to repro this, but in some cases I've seen it's necessary to kill the LISTEN manually with `pg_terminate_backend` to receive notifications again (maybe https://github.com/PostgREST/postgrest/issues/4670 will solve it).

The above gave me an idea https://github.com/PostgREST/postgrest/issues/4863.

> The actual queries we are running are really an implementation detail, nothing else. We should not guarantee their shape just because of observability.

If we all agree on this we should document it somewhere, maybe on https://docs.postgrest.org/en/v14/#releases.

Comment (laurenceisla) [reply CHANGELOG.md]: > I don't think the fact that Laurence created an issue about my observation 

Ah, sorry, I actually didn't notice your observation, I'd have continued the conversation there instead of making a separate issue.

> TLDR: If you really need a way to identify PostgREST sessions, take the ability to freely change application_name away and force it.

> The above gave me an idea #4863.

Yeah, agree that changing the `application_name` is the better solution here. So I think we can close #4857 issue as not-planned in favor of the feature request above?

File: test/observability/Observation/ListenerSpec.hs (hunk 1 above)
Comment (mkleczek) [reply test/observability/Observation/ListenerSpec.hs]: Fixed.

I still think `Hspec` tests of listener are more convenient thanks to the new observability testing infra but in this case it is not necessary.
Will leave #4860 as a separate PR.

File: CHANGELOG.md (hunk 2 above)
Comment (steve-chavez) [reply CHANGELOG.md]: > I really think we should not guarantee any of that. The actual queries we are running are really an implementation detail, nothing else. We should not guarantee their shape just because of observability.

The implementation details of the maintenance queries must also be known currently as argued on https://github.com/PostgREST/postgrest/issues/4864.

> Yeah, agree that changing the application_name is the better solution here. So I think we can close https://github.com/PostgREST/postgrest/issues/4857 issue as not-planned in favor of the feature request above?

Disagree, I think this fix should still go and on the next major we can be explicit that administrators should not rely on queries shapes since they're implementation details. We have to solve both #4863 and #4864 before that announcement IMO.

File: test/io/test_io.py [hunk 3]
```diff
@@ -690,6 +691,39 @@ def test_admin_ready_w_channel(defaultenv):
...
+                "psql",
+                "--set",
+                "ON_ERROR_STOP=1",
+                "--tuples-only",
+                "--no-align",
+                "-c",
+                query,
+            ],
+            text=True,
+        ).strip()
```
Comment (steve-chavez) [inline test/io/test_io.py:722]: Hm, so far our way of doing this type of test has been through RPCs put in the fixtures. I'm undecided which method is better, can this `psql` fail in another way somehow? How is it obtaining the db uri?

Comment (mkleczek) [reply test/io/test_io.py:722]: > Hm, so far our way of doing this type of test has been through RPCs put in the fixtures. I'm undecided which method is better, can this `psql` fail in another way somehow? How is it obtaining the db uri?

I've taken it from: https://github.com/mkleczek/postgrest/blob/b8f83bdbb4b0ba7adca6563758c292616af7b0b9/test/io/test_io.py#L1456
but stripped explicit `PG*` environment variables access since its redundant.

Comment (steve-chavez) [reply test/io/test_io.py:722]: Fair enough, let's leave it as is

File: CHANGELOG.md [hunk 4]
```diff
@@ -21,6 +21,7 @@ All notable changes to this project will be documented in this file. From versio
 - Fix login with uppercase and mixed case role names by @taimoorzaeem in #4678
 - Remove automatic transaction retries on `40001 (serialization_failure)` errors to prevent replication lag by @laurenceisla in #3673
 - Fix unexpected results when embedding and filtering the same table more than once by @laurenceisla in #4075
+- Make sure `LISTEN <db-channel>` query is present in pg_stat_activity row corresponding to session established by notification listening thread by @mkleczek in #4857 #4859
```
Comment (steve-chavez) [inline CHANGELOG.md]:
```suggestion
- Restore Listener query shape so it can be found in pg_stat_activity by @mkleczek in #4857 #4859
```

**Review by steve-chavez — APPROVED** [review]
