### PR TITLE
fix: Error when requesting `count` with Null embed filters

### LINKED ISSUE #2846: Null filtering on embedded resources throws `column does not exist` error when using `Prefer: count=exact`
### Environment

* PostgreSQL version: (if using docker, specify the image)
* Docker image: supabase/postgres:15.1.0.90
* PostgREST version: (if using docker, specify the image)
* image: postgrest/postgrest:latest (A little tricky here, I'm selfhosting supabase with the latest postgREST!)
* Operating system: Mac

### Description of issue

Ex.
```
-- Create the "people" table
CREATE TABLE people (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  -- Add other columns as needed
);

-- Create the "donations" table
CREATE TABLE donations (
  id SERIAL PRIMARY KEY,
  person_id INTEGER REFERENCES people(id),
  amount NUMERIC,
  -- Add other columns as needed
);

```

```
curl 'http://localhost:8000/rest/v1/people?select=*%2Cdonations%28*%29&or=%28and%28donations.not.is.null%29%29&donations.or=(and%28amount.eq.1%29)'
```

...responds with the correct items.

```
curl 'http://localhost:8000/rest/v1/people?select=*%2Cdonations%28*%29&or=%28and%28donations.not.is.null%29%29&donations.or=(and%28amount.eq.1%29)'
-H "Prefer: count=exact"
```

Responds:

`{code: "42703", details: null, hint: null, message: "column "people_donations_1" does not exist"}`

This seems to hold for count estimated or exact and other combinations or filtering against related tables.

So in effect we cannot count the rows alongside a filter against a joined table.

### PR DESCRIPTION
**Pull request by laurenceisla**
Fixes #2846

### CODE REVIEW

File: src/PostgREST/Query/QueryBuilder.hs [hunk 1]
```diff
@@ -216,6 +216,16 @@ readPlanToCountQuery (Node ReadPlan{from=mainQi, fromAlias=tblAlias, where_=logi
...
+    pgFmtLogicTree' qi' (CoercibleExpr hasNot op forest') = SQL.sql notOp <> " (" <> intercalateSnippet (opSql op) (pgFmtLogicTree' qi' <$> forest') <> ")"
+      where
+        notOp =  if hasNot then "NOT" else mempty
+
+        opSql And = " AND "
+        opSql Or  = " OR "
+    pgFmtLogicTree' _ (CoercibleStmnt (CoercibleFilterNullEmbed hasNot fld)) =
+      "(" <> maybe "" readPlanToCountQuery (nullEmbedRel fld) <> ") IS " <> (if hasNot then "NOT" else mempty) <> " NULL"
+    pgFmtLogicTree' qi' stmnt = pgFmtLogicTree qi' stmnt
+    nullEmbedRel fld = find (\(Node ReadPlan{relAggAlias} _) -> fld == relAggAlias) forest
```
Comment (steve-chavez) [inline src/PostgREST/Query/QueryBuilder.hs:228]: :open_mouth: Oh, I thought it would be a more involved change. Can you show the resulting query?

Comment (laurenceisla) [reply src/PostgREST/Query/QueryBuilder.hs:228]: The full resulting query is like this:

```bash
$ curl "http://localhost:3000/films?select=*,actors(*)&actors=not.is.null"
```

```sql
-- not.is.null

WITH pgrst_source AS
  (SELECT "api"."films".*,
          COALESCE("films_actors_1"."films_actors_1", '[]') AS "actors"
   FROM "api"."films"
   LEFT JOIN LATERAL
     (SELECT json_agg("films_actors_1") AS "films_actors_1"
      FROM
        (SELECT "api"."actors".*
         FROM "api"."actors",
              "api"."roles"
         WHERE "api"."roles"."actor_id" = "api"."actors"."id"
           AND "api"."roles"."film_id" = "api"."films"."id" LIMIT $1
         OFFSET $2) AS "films_actors_1") AS "films_actors_1" ON TRUE
   WHERE "films_actors_1" IS NOT NULL LIMIT $3
   OFFSET $4) ,
pgrst_source_count AS
  (SELECT 1
   FROM "api"."films"
   WHERE
       (SELECT 1
        FROM "api"."actors",
             "api"."roles"
        WHERE "api"."roles"."actor_id" = "api"."actors"."id"
          AND "api"."roles"."film_id" = "api"."films"."id") IS NOT NULL)
SELECT
  (SELECT pg_catalog.count(*)
   FROM pgrst_source_count) AS total_result_set,
       pg_catalog.count(_postgrest_t) AS page_total,
       coalesce(json_agg(_postgrest_t), '[]') AS body,
       nullif(current_setting('response.headers', TRUE), '') AS response_headers,
       nullif(current_setting('response.status', TRUE), '') AS response_status
FROM
  (SELECT *
   FROM pgrst_source) _postgrest_t
```

Comment (laurenceisla) [reply src/PostgREST/Query/QueryBuilder.hs:228]: The `pgrst_source_count` is the relevant part. I used `IS NOT NULL` instead of `EXISTS` because I wanted to handle the edge case mentioned here: https://github.com/PostgREST/postgrest/issues/2800.

But this does not work for that case, because the `SELECT 1` will never be `NOT NULL`, we need the full `SELECT` to verify that.

In any case, we need to decide whether to translate `table=not.is.null` to `NOT (table IS NULL)` or go with what we're using now: `table IS NOT NULL`. This comment by Wolfgang in the same issue gives a better context: https://github.com/PostgREST/postgrest/issues/2800#issuecomment-1562620508

Comment (laurenceisla) [reply src/PostgREST/Query/QueryBuilder.hs]: Now that #2800 is completed, the new query can now use `EXISTS` for `not.is.null` and `NOT EXISTS` for `is.null`. The resulting query (the `pgrst_source_count`) now would be:

```sql
  WITH pgrst_source AS
  (SELECT "api"."films".*,
          COALESCE("films_actors_1"."films_actors_1", '[]') AS "actors"
   FROM "api"."films"
   LEFT JOIN LATERAL
     (SELECT json_agg("films_actors_1") AS "films_actors_1"
      FROM
        (SELECT "api"."actors".*
         FROM "api"."actors",
              "api"."roles"
         WHERE "api"."roles"."actor_id" = "api"."actors"."id"
           AND "api"."roles"."film_id" = "api"."films"."id" LIMIT $1
         OFFSET $2) AS "films_actors_1") AS "films_actors_1" ON TRUE
   WHERE "films_actors_1" IS DISTINCT FROM NULL LIMIT $3
   OFFSET $4) ,
     pgrst_source_count AS
  (SELECT 1
   FROM "api"."films"
   WHERE EXISTS
       (SELECT 1
        FROM "api"."actors",
             "api"."roles"
        WHERE "api"."roles"."actor_id" = "api"."actors"."id"
          AND "api"."roles"."film_id" = "api"."films"."id"))
SELECT
  (SELECT pg_catalog.count(*)
   FROM pgrst_source_count) AS total_result_set,
       pg_catalog.count(_postgrest_t) AS page_total,
       coalesce(json_agg(_postgrest_t), '[]') AS body,
       nullif(current_setting('response.headers', TRUE), '') AS response_headers,
       nullif(current_setting('response.status', TRUE), '') AS response_status
FROM
  (SELECT *
   FROM pgrst_source) _postgrest_t
```

File: test/spec/Feature/Query/RelatedQueriesSpec.hs [hunk 2]
```diff
@@ -275,3 +276,37 @@ spec = describe "related queries" $ do
...
+          {"name":"Windows 10", "clients":{"name":"Microsoft"}},
+          {"name":"IOS", "clients":{"name":"Apple"}},
+          {"name":"OSX", "clients":{"name":"Apple"}}
+        ]|]
+        { matchStatus  = 200
+        , matchHeaders = [ matchContentTypeJson
+                         , "Content-Range" <:> "0-3/4" ]
+        }
+      request methodGet "/projects?select=name,clients()&clients=is.null"
+        [("Prefer", "count=exact")] ""
```
Comment (steve-chavez) [inline test/spec/Feature/Query/RelatedQueriesSpec.hs:295]: Is `count=planned` and `count=estimated` relevant here? Maybe we could add a test to ensure they work too?

Comment (laurenceisla) [reply test/spec/Feature/Query/RelatedQueriesSpec.hs:295]: Yes, those didn't work either.

**Review by steve-chavez — APPROVED** [review]

**Comment by zachblume** [comment]
Thank you @laurenceisla for this fix! Appreciate it!
