### PR TITLE
fix: RPC returning tables not embedding correctly when using overloaded functions for computed relationships

### LINKED ISSUE #2963: Ressource embedding with stored procedures: Error recognising unique overloaded functions
### Environment

* PostgreSQL version: PostgreSQL 14.9 
* PostgREST version: Docker postgrest/postgrest:v11.2.0
* Operating system: Ubuntu 22.04.1

### Description of issue

According to docs ressource embedding in RPC's is supported when returning a table type.  I want to use this with computed relations and overloaded functions (same function name with different table types) . I can only get this to work with only one unique function name.

#### Create table types
```sql
CREATE TABLE api.test as 
SELECT'test' as desc;
CREATE TABLE api.test1 as 
SELECT
'test1' as desc
;
CREATE TABLE api.embedthis AS
SELECT * FROM generate_series(1,10) AS id;
```
#### Create computed relation embed(api.test) 

```sql
CREATE FUNCTION api.embed(api.test) RETURNS SETOF api.embedthis  AS  $$
    SELECT * FROM api.embedthis limit 1;
$$ STABLE LANGUAGE sql;
```
#### Test in basic table type:
```
http://localhost:3000/test?select=*,embed(*)
```
Response ok
```json
[
  {
    "desc": "test",
    "embed": [
      {
        "id": 1
      }
    ]
  }
]
```
#### Use computed relation in a stored procedure

```sql
DROP FUNCTION IF EXISTS api.myrpc(); 
CREATE FUNCTION  api.myrpc() RETURNS setof api.test
 LANGUAGE sql
AS $function$
  SELECT  * from api.test;
$function$;
```
```
http://localhost:3000/rpc/myrpc?select=*,embed(*)
```
Embbeded response is working as expected
```json
[
  {
    "desc": "test",
    "embed": [
      {
        "id": 1
      }
    ]
  }
]
```

#### create overloaded function embed(api.test1) 

```sql
CREATE FUNCTION api.embed(api.test1) RETURNS SETOF api.embedthis  AS  $$
    SELECT * FROM api.embedthis limit 2;
$$ STABLE LANGUAGE sql;
```
#### Test overloaded function embed(api.test1) 
```
http://localhost:3000/test1?select=*,embed(*)
```
Embedded response working as expected
```json
[
  {
    "desc": "test1",
    "embed": [
      {
        "id": 1
      },
      {
        "id": 2
      }
    ]
  }
]
```
Test embedded relation in RPC:
```
http://localhost:3000/rpc/myrpc?select=*,embed(*)
```
Embedded relation not working anymore
```json
{
  "code": "42725",
  "details": null,
  "hint": "Could not choose a best candidate function. You might need to add explicit type casts.",
  "message": "function api.embed(record) is not unique"
}
```

### PR DESCRIPTION
**Pull request by laurenceisla**
Closes #2963

### CODE REVIEW

File: test/spec/Feature/Query/ComputedRelsSpec.hs [hunk 1]
```diff
@@ -192,3 +192,29 @@ spec = describe "computed relationships" $ do
...
+      get "/items?select=*,computed_rel_overload(*)&limit=1"
+        `shouldRespondWith`
+        [json|
+          [{"id":1,"computed_rel_overload":[{"id":1}]}]
+        |] { matchHeaders = [matchContentTypeJson] }
+      get "/items2?select=*,computed_rel_overload(*)&limit=1"
+        `shouldRespondWith`
+        [json|
+          [{"id":1,"computed_rel_overload":[{"id":1},{"id":2}]}]
+        |] { matchHeaders = [matchContentTypeJson] }
```
Comment (laurenceisla) [inline test/spec/Feature/Query/ComputedRelsSpec.hs:208]: These tests work before the changes, but I added them for completion.

File: src/PostgREST/Query/QueryBuilder.hs [hunk 2]
```diff
@@ -242,8 +242,8 @@ getQualifiedIdentifier rel mainQi tblAlias = case rel of
 fromF :: Maybe Relationship -> QualifiedIdentifier -> Maybe Alias -> SQL.Snippet
 fromF rel mainQi tblAlias = "FROM " <>
   (case rel of
-    Just ComputedRelationship{relFunction,relTable} -> fromQi relFunction <> "(" <> pgFmtIdent (qiName relTable) <> ")"
-    _                                               -> fromQi mainQi) <>
+    Just ComputedRelationship{relFunction,relTableAlias,relTable} -> fromQi relFunction <> "(" <> pgFmtIdent (qiName relTableAlias) <> "::" <> fromQi relTable <> ")"
```
Comment (steve-chavez) [inline src/PostgREST/Query/QueryBuilder.hs:245]: How about adding a comment here, like: 

```
due to the use of CTEs we need to cast, see https://github.com/PostgREST/postgrest/issues/2963
```

**Review by steve-chavez — APPROVED** [review]
LGTM. Don't forget the CHANGELOG!
