### PR TITLE
fix: call `pg_notification_queue_usage()` automatically when the LISTEN channel bug is detected

### LINKED ISSUE #3147: LISTEN channel stops working due to postgres bug
## Problem

This just happened on a production instance. `NOTIFY pgrst` wasn't triggering a schema cache reload while according to `pg_stat_activity` the `LISTEN` channel was up for several days:

```sql
select * from pg_stat_activity where application_name ilike '%postgrest%' and query ilike '%listen%';
-[ RECORD 1 ]----+------------------------------
datid            | 12974
datname          | postgres
pid              | 1368652
leader_pid       | 
usesysid         | 16665
usename          | authenticator
application_name | postgrest
client_addr      | 127.0.0.1
client_hostname  | 
client_port      | 53768
backend_start    | 2023-12-28 11:23:50.967734+00
xact_start       | 
query_start      | 2023-12-28 11:23:50.985951+00
state_change     | 2023-12-28 11:23:50.986375+00
wait_event_type  | Client
wait_event       | ClientRead
state            | idle
backend_xid      | 
backend_xmin     | 
query_id         | 7372465010149019010
query            | LISTEN "pgrst"
backend_type     | client backend
``` 

Further investigation lead to finding this PostgreSQL bug:

```sql
postgres=# listen pgrst;
ERROR:  could not access status of transaction 1044524795
DETAIL:  Could not open file "pg_xact/03E4": No such file or directory.

postgres=# listen pgrst;
ERROR:  could not access status of transaction 1044524795
DETAIL:  Could not open file "pg_xact/03E4": No such file or directory.

postgres=# listen xx;
ERROR:  could not access status of transaction 1044524795
DETAIL:  Could not open file "pg_xact/03E4": No such file or directory.

postgres=# listen yy;
ERROR:  could not access status of transaction 1044524795
DETAIL:  Could not open file "pg_xact/03E4": No such file or directory.
```

More details:

- https://dba.stackexchange.com/questions/325104/error-could-not-access-status-of-transaction-could-not-open-file-pg-xact-0029
- https://www.postgresql.org/message-id/flat/VE1PR03MB531295B1BDCFE422441B15FD92499%40VE1PR03MB5312.eurprd03.prod.outlook.com#7e36d1fdca921b5292e92c7017984ffa

So seems the LISTEN channel is broken. I can't reproduce this locally though.

The only way to repair this error is by restarting the PostgreSQL instance AFAICT.

## Workaround

Killing the LISTEN channel will force PostgREST to reload.

```sql
select pg_terminate_backend(pid) from pg_stat_activity 
where application_name ilike '%postgrest%' and query ilike '%listen%';
```

## Further measures

Do we have any way to prevent this? Would a shorter lifetime in the LISTEN channel help?

### PR DESCRIPTION
**Pull request by laurenceisla**
(WIP) Closes #3147

Implements what is mentioned in https://github.com/PostgREST/postgrest/issues/3147#issuecomment-4289368179.

### CODE REVIEW

**Comment by laurenceisla** [comment]
I applied the same steps to reproduce mentioned here: https://github.com/PostgREST/postgrest/pull/4581#issuecomment-3690610592.

This initial attempt to automatically fix the issue seems to work. The full logs look like this:

```console
28/Apr/2026:20:13:11 -0500: Starting PostgREST 15 (pre-release)...
28/Apr/2026:20:13:11 -0500: Admin server listening on 0.0.0.0:3001
28/Apr/2026:20:13:11 -0500: API server listening on 0.0.0.0:3000
28/Apr/2026:20:13:11 -0500: Successfully connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
28/Apr/2026:20:13:11 -0500: Connection Pool initialized with a maximum size of 1 connections
28/Apr/2026:20:13:11 -0500: Failed listening for database notifications on the "pgrst" channel. ERROR:  could not access status of transaction 742 DETAIL:  Could not open file "pg_xact/0000": No such file or directory.
28/Apr/2026:20:13:11 -0500: This is likely a bug in the notification queue, executing the following to solve it: SELECT pg_notification_queue_usage();
28/Apr/2026:20:13:11 -0500: Retrying listening for database notifications in 1 seconds...
28/Apr/2026:20:13:11 -0500: Config reloaded
28/Apr/2026:20:13:11 -0500: Schema cache queried in 24.8 milliseconds
28/Apr/2026:20:13:11 -0500: Schema cache loaded 1 Relations, 0 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 487 Timezones
28/Apr/2026:20:13:11 -0500: Schema cache loaded in 0.4 milliseconds
28/Apr/2026:20:13:12 -0500: Listener connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit on "localhost:6432" and listening for database notifications on the "pgrst" channel
28/Apr/2026:20:13:12 -0500: Successfully connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
28/Apr/2026:20:13:12 -0500: Connection Pool initialized with a maximum size of 1 connections
28/Apr/2026:20:13:12 -0500: Config reloaded
28/Apr/2026:20:13:12 -0500: Schema cache queried in 35.1 milliseconds
28/Apr/2026:20:13:12 -0500: Schema cache loaded 1 Relations, 0 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 487 Timezones
28/Apr/2026:20:13:12 -0500: Schema cache loaded in 0.3 milliseconds
```

File: src/PostgREST/Config/Database.hs [hunk 1]
```diff
@@ -203,3 +204,12 @@ param = HE.param . HE.nonNullable
 
 arrayParam :: HE.Value a -> HE.Params [a]
 arrayParam = param . HE.foldableArray . HE.nonNullable
+
+-- Used to fix a Postgres bug in the listener (see https://github.com/PostgREST/postgrest/issues/3147#issuecomment-3494591361)
+-- This query advances the async notification query tail, which solves this issue
+callNotifQueryUsage :: Session Double
```
Comment (mkleczek) [inline src/PostgREST/Config/Database.hs]: I would leave it local to the `Listener` module. There is no need to put it here as it is not reusable and only enhances coupling between `Listener` and `Database` modules.

It is different from `pgVersionStatement` which is reused across multiple modules.

File: CHANGELOG.md [hunk 2]
```diff
@@ -14,6 +14,7 @@ All notable changes to this project will be documented in this file. From versio
 - Add `Vary` header to responses by @develop7 in #4609
 - Add config `db-timezone-enabled` for optional querying of timezones by @taimoorzaeem in #4751
 - Log schema cache queries timings on `log-level=debug` by @steve-chavez in #4805
+- Call `pg_notification_queue_usage()` automatically when the LISTEN channel bug is detected by @laurenceisla in #3147
```
Comment (wolfgangwalther) [inline CHANGELOG.md]: As a user, I have no idea what that does for me.

Isn't this a bug fix to solve the "LISTEN channel bug" instead?

Comment (laurenceisla) [reply CHANGELOG.md]: > As a user, I have no idea what that does for me.

Right, fixing that.

> Isn't this a bug fix to solve the "LISTEN channel bug" instead?

Do you mean if this should be put under "Fixed"? Not sure if a bug fix for us, it's a PostgreSQL bug that we  work around by executing that query, so I figured it'd be better as a feature.

Comment (wolfgangwalther) [reply CHANGELOG.md]: The user ultimately doesn't care whether the bug is rooted in PostgreSQL or in PostgREST. To them this is just a bug. If we work around a PostgreSQL bug - it's still a fix.

(the changelog entry could still mention "this works around a PostgreSQL bug" or so, no problem with that - it's just not a new feature we gain)

Comment (laurenceisla) [reply CHANGELOG.md]: Hmmm... not oposed, I'll also change it.

Comment (steve-chavez) [reply CHANGELOG.md]: Also agree that this should be a `fix`, I've updated the PR title.

**Comment by laurenceisla** [comment]
I think this should be ready for review. I reproduced the issue and tested that the notification channel automatically recovers, and that the different `NOTIFY pgrst...` work right after:

<details><summary>See logs</summary>
<p>

```console
30/Apr/2026:12:35:02 -0500: Starting PostgREST 15 (pre-release)...
30/Apr/2026:12:35:02 -0500: Admin server listening on 0.0.0.0:3001
30/Apr/2026:12:35:02 -0500: API server listening on 0.0.0.0:3000
30/Apr/2026:12:35:02 -0500: Successfully connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
30/Apr/2026:12:35:02 -0500: Connection Pool initialized with a maximum size of 1 connections
# Logs the failure here:
30/Apr/2026:12:35:02 -0500: Failed listening for database notifications on the "pgrst" channel. ERROR:  could not access status of transaction 753 DETAIL:  Could not open file "pg_xact/0000": No such file or directory.
30/Apr/2026:12:35:02 -0500: This is likely a bug in the notification queue, executing the following to solve it: SELECT pg_notification_queue_usage();
# It executes the fix and automatically recovers the listener:
30/Apr/2026:12:35:02 -0500: Retrying listening for database notifications in 1 seconds...
30/Apr/2026:12:35:02 -0500: Config reloaded
30/Apr/2026:12:35:02 -0500: Schema cache queried in 38.3 milliseconds
30/Apr/2026:12:35:02 -0500: Schema cache loaded 1 Relations, 0 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 487 Timezones
30/Apr/2026:12:35:02 -0500: Schema cache loaded in 0.5 milliseconds
30/Apr/2026:12:35:03 -0500: Listener connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit on "localhost:6432" and listening for database notifications on the "pgrst" channel
30/Apr/2026:12:35:03 -0500: Successfully connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
30/Apr/2026:12:35:03 -0500: Connection Pool initialized with a maximum size of 1 connections
30/Apr/2026:12:35:03 -0500: Config reloaded
30/Apr/2026:12:35:03 -0500: Schema cache queried in 43.0 milliseconds
30/Apr/2026:12:35:03 -0500: Schema cache loaded 1 Relations, 0 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 487 Timezones
30/Apr/2026:12:35:03 -0500: Schema cache loaded in 0.3 milliseconds
# Executed: NOTIFY pgrst, 'reload schema';
30/Apr/2026:12:35:30 -0500: Received a schema cache reload message on the "pgrst" channel
30/Apr/2026:12:35:30 -0500: Successfully connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
30/Apr/2026:12:35:30 -0500: Connection Pool initialized with a maximum size of 1 connections
30/Apr/2026:12:35:30 -0500: Config reloaded
30/Apr/2026:12:35:30 -0500: Schema cache queried in 36.4 milliseconds
30/Apr/2026:12:35:30 -0500: Schema cache loaded 1 Relations, 0 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 487 Timezones
30/Apr/2026:12:35:30 -0500: Schema cache loaded in 0.2 milliseconds
# Executed: NOTIFY pgrst, 'reload config';
30/Apr/2026:12:35:36 -0500: Received a config reload message on the "pgrst" channel
30/Apr/2026:12:35:36 -0500: Config reloaded
# Executed: NOTIFY pgrst;
30/Apr/2026:12:35:40 -0500: Received a schema cache reload message on the "pgrst" channel
30/Apr/2026:12:35:40 -0500: Successfully connected to PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
30/Apr/2026:12:35:40 -0500: Connection Pool initialized with a maximum size of 1 connections
30/Apr/2026:12:35:40 -0500: Config reloaded
30/Apr/2026:12:35:40 -0500: Schema cache queried in 57.2 milliseconds
30/Apr/2026:12:35:40 -0500: Schema cache loaded 1 Relations, 0 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 487 Timezones
30/Apr/2026:12:35:40 -0500: Schema cache loaded in 0.4 milliseconds
# Made some requests:
127.0.0.1 - postgres [30/Apr/2026:12:36:27 -0500] "GET / HTTP/1.1" 200 3486 "" "curl/8.7.1"
127.0.0.1 - postgres [30/Apr/2026:12:36:39 -0500] "GET /test HTTP/1.1" 200 10 "" "curl/8.7.1"
```

</p>
</details>

**Comment by mkleczek** [comment]
> I think this should be ready for review. I reproduced the issue and tested that the notification channel automatically recovers, and that the different `NOTIFY pgrst...` work right after:
> 

That's really cool. Question: how did you reproduce the PostgreSQL bug? Would it be possible to create a test case for it?

**Comment by laurenceisla** [comment]
> That's really cool. Question: how did you reproduce the PostgreSQL bug? Would it be possible to create a test case for it?

Basically the same steps done here: https://github.com/PostgREST/postgrest/pull/4581#issuecomment-3690610592. I used docker-compose here for a primary and replica. Personally, I found it difficult to add a test case, although in theory maybe we could. The part that takes a bit of time (resources too?) is the pgbench step, not sure how it will run in CI.

**Comment by steve-chavez** [comment]
> Basically the same steps done here: https://github.com/PostgREST/postgrest/pull/4581#issuecomment-3690610592. I used docker-compose here for a primary and replica. Personally, I found it difficult to add a test case, although in theory maybe we could. The part that takes a bit of time (resources too?) is the pgbench step, not sure how it will run in CI.

Looked at how it's done and indeed it looks too complex, specially the part about running pgbench for some minutes. Since this is a postgres bug not a PostgREST one, I think it's fine to not have a test.

**Review by steve-chavez — APPROVED** [review]

File: src/PostgREST/Logger.hs [hunk 3]
```diff
@@ -188,8 +188,8 @@ observationMessages = \case
       either showListenerConnError showListenerException listenErr
   DBListenRetry delay ->
     pure $ "Retrying listening for database notifications in " <> (show delay::Text) <> " seconds..."
-  DBListenBugHint ->
-    pure "HINT:  This is likely a bug in the notification queue, try executing the following to solve it: select pg_notification_queue_usage();"
+  DBListenBugCallQueryFix ->
+    pure "This is likely a bug in the notification queue, executing the following to solve it: SELECT pg_notification_queue_usage();"
```
Comment (steve-chavez) [inline src/PostgREST/Logger.hs]:
```suggestion
    pure "This is likely a PostgreSQL bug in the notification queue, executing the following to try to solve it: SELECT pg_notification_queue_usage();"
```

**Review by steve-chavez — CHANGES_REQUESTED** [review]

**Review by steve-chavez — APPROVED** [review]
